### ISSUE TITLE
Section 4.3.2: Include a description of improvements in Release 17

### ISSUE THREAD

**Issue by jordijoangimenez** [5G-MAG/Standards#10]
**Describe the bug**
Information on Rel-17 improvements to be added

**Step 2: Suggested solution**
Provide a short list of additions according to Rel-17, related to LTE_terr_bcast_bands_part1

**Comment by rjb1000** [comment]
Please could you point out the clauses you think need to be updated in the description above?

**Comment by jordijoangimenez** [comment]
Refer to: [CR_ETSI103720_Issue10.docx](https://member.5g-mag.com/wg/CD-T/document/710)

**Comment by jordijoangimenez** [comment]
RESOLVED - it can still be reviewed
