### ISSUE TITLE
TS26.501 - Potential mistake in definition of "Triggering downlink media streaming access reporting" 

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/Standards#100]
# Description
Clause 5.11.5 of TS26.501 Version 18.3.1 defines the mechanism to trigger downlink media streaming access reporting. The specification states:

> Reports shall be sent by the 5GMSd AS to the Data Collection AS as indicated in the data collection client configuration
obtained using the procedure defined in clause 5.11.1.

Should this be "Data Collection **AF**" instead of "Data Collection **AS**" to align with clause 5.11.1?

**Comment by rjb1000** [comment]
Yes, @dsilhavy, that looks like a simple typo.

**Comment by rjb1000** [comment]
This affects TS 26.501 Rel-17 too.

**Comment by rjb1000** [comment]
Pushed this into the next meeting cycle. It should be possible to deal with it there.

**Comment by rjb1000** [comment]
Initial Change Request drafted and contributed to SA4 _ad hoc_ meeting for possible endorsement:

- TS 26.501
  - Rel-17: **CR0087** "[5GMSA, TEI17] Miscellaneous corrections" in [S4aI240014](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/Docs/S4aI240014.zip).
  - Rel-18: _To be drafted if the above is endorsed._

**Comment by rjb1000** [comment]
Change Request endorsed by SA4 _ad hoc_ meeting.

To be submitted (along with Rel-18 derivative) to forthcoming SA4#127-e-bis meeting for formal agreement.

**Comment by rjb1000** [comment]
Change Requests contributed to SA4#127-bis-e for agreement:
* TS 26.501
  * Rel-16: *Not affected*.
  * Rel-17: **CR0087**r2 "[5GMSA, TEI17] Miscellaneous corrections" in [S4-240625](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524829).
  * Rel-18: *Clause 5.11.5 voided by CR0089*.

**Comment by rjb1000** [comment]
Change Request agreed without revision at SA4#127-bis-e:

* TS 26.501
  * Rel-16: *Not affected*.
  * Rel-17: **CR0087**r2 "[5GMSA, TEI17] Miscellaneous corrections" in [S4-240625](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524829).
  * Rel-18: *Clause 5.11.5 voided by CR0089*.

This goes to SA#104 for approval.

**Comment by rjb1000** [comment]
New specification versions published following approval of CRs at SA#104:
- TS 26.501
  - Rel-16: _Not affected._
  - Rel-17: [V17.10.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.501/26501-ha0.zip).
    Rel-18: _Clause 5.11.5 voided by CR0089._
