### ISSUE TITLE
TS 26.512: M5 Dynamic Policies API and Network Assistance API - Potential inconsistency in the resource structure

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/Standards#105]
# Description
TS 26.512 17.70 defines the M5 Dynamic Policies API and the M5 Network Assistance API and their corresponding resource structures:

* `{apiRoot}/3gpp-m5/{apiVersion}/dynamic-policies/`
* `{apiRoot}/3gpp-m5/{apiVersion}/network-assistance/`

The DynamicPolicy resource that is sent as a payload in the `POST` request is defined in Section 11.5.3.1 and contains a `provisioningSessionId`. The same is true for the provisioning of a new network assistance session, as can be seen in the defintion of the NetworkAssistanceSession resource in Section 11.6.3.

Compared to other API endpoints such as the one for consumption reporting and metrics reporting the `provisioningSessionId` is not part of the resource structure. As an example:

* `{apiRoot}/3gpp-m5/{apiVersion}/metrics-reporting/{provisioningSessionId}/{metricsReportingConfigurationId}`

# Discussion

I was wondering what the reason was to place the `provisioningSessionId` in the `POST` body for dynamic policies and network assistance. This seems to be inconsistent to what was done for metrics reporting and consumption reporting.  

As an example, can we add the `provisioningSessionId` as a sub-resource path to the `POST` request of the Dynamic Policies API? From my understanding the `provisioningSessionId` is not needed for the `GET`, `PUT`, `PATCH` and `DELETE` operations as we are using a unique `dynamicPolicyId`. Consequently, we can not add the `provisioningSessionId` to the base URL path.

**Comment by rjb1000** [comment]
Thinking about this one...

**Comment by rjb1000** [comment]
As an adjunct of this design, *{provisioningSessionId}* needs to become a read-only property of the *DynamicPolicy* and *NetworkAssistanceSession* resources that are created by the Media AF on request from the Media Session Handler.

**Comment by rjb1000** [comment]
Decided not to pursue this in Rel-16 or Rel-17 because it would break backwards compatibility of the APIs.
