### ISSUE TITLE
Demodulation Receiver Requirements

### ISSUE THREAD

**Issue by haudiobe** [5G-MAG/Standards#11]
**Step 1: Is your feature request related to a problem? Please describe.**
Receiver implementations need to fulfill certain requirements for proper network planning. In particular, dual antenna reception is a common functionality, including interference cancellation. This issue is particularly relevant for re-use 1 cases.

**Step 2: Describe the solution you'd like**
Add receiver requirements to TS 103 720 for dual antenna and demodulation based on 3GPP requirements in TS 36.101, clause 10.3 and 10.4.

**Step 3: Describe alternatives you've considered**
Implementations may address this, but it is unclear whether implementors can extract all 3GPP requirements sufficiently for broadcast reception.

**Step 4: Additional context**

**Step 5: Choose related standard/project (right side)**
ETSI TS 103 720 next version

**Comment by jordijoangimenez** [comment]
@haudiobe to work on a draft CR

**Comment by haudiobe** [comment]
This is from TS 36.101. All the channels are 1x2, which means 1 Tx 2 Rx antennas, except for 0.37kHz (which is intended for rooftop, so single Rx):

![receiver-req](https://user-images.githubusercontent.com/2828689/195595252-cffee0e5-4271-4116-b4cf-d31c964e58a7.png)

**Comment by haudiobe** [comment]
Note that this extension should go clause 7.3.8 which already talks about demodulation requirements.

7.3.8	Demodulation requirements
5G Broadcast Receivers shall support the demodulation requirements in ETSI TS 136 101 [14], clause 10.4.

Add some text to document some specifics.

**Comment by jordijoangimenez** [comment]
I'll do a CR based on the info. Thanks!

**Comment by haudiobe** [comment]
CR provided here: https://member.5g-mag.com/wg/CD-T/document/896?downloadRevision=1429

**Comment by jordijoangimenez** [comment]
Adopted in https://member.5g-mag.com/wg/CD-T/document/779
