### ISSUE TITLE
TS 26.532: Clarification on dataPackagingStrategy format and common packing attributes

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/Standards#112]
In TS 26.532 v18.1.0 Table 5.4.2.2-1 there is a `dataPackagingStrategy` string that forms part of the *DataReportingRule* which is used to convey report packing attributes. However, apart from the brief description in the table, there appears to be a lack of information surrounding this field.

- What is the format of this string?
- Is there a set of base packing strategy attributes that can be used, e.g. maximum data size, maximum records per report?
- What are the packing strategies available for the base data report types defined in TS 26.532 v18.1.0 in Annex A and Table 7.3.2.3-1?
- What are the default packing strategies for these report types if a strategy is not defined in the *DataReportingRule*?

**Comment by rjb1000** [comment]
It's difficult to come up with a sensible design of data packaging strategies for the generic data reporting domains defined in TS 26.532 for exposure to the NWDAF.

Defining data packaging strategies could be based on practical implementation experience, but we are not planning to address this issue for the abovementioned generic data reporting domains as part of the 5G-MAG reference implementation.

For the 5G Media Streaming data reporting domains, this would more likely be addressed in TS 26.512:
- *MS_ACCESS_ACTIVITY*
  - What different packaging strategies would you suggest for reporting of media streaming access logs by the 5GMS AS to the Data Collection AF, @davidjwbbc?
- *MS_ANBR_NETWORK_ASSISTANCE* (Rel-18 onwards)
   - We could ask @zooksy to look into different strategies for packing ANBR Network Assistance invocations into UE data reports sent to the Data Collection AF.

The most minimal change I can think of for TS 26.532 is an additional clause 10 that specifies data packaging strategies for each of the data reporting domains defined in table 7.3.3.1-1. This clause would be cross-referenced from clauses 4.2.6 (Indirect data reporting) and 4.3.3 (Direct data reporting). There would be a subclause 10.x for each of the data reporting domains as follows:
- For each "generic" data reporting domain the text would state that no data packaging strategies are defined in this release and that data reporting client implementations are free to choose whatever packaging strategy they see fit.
- For each 5GMS data reporting domain the text would reference TS 26.512.
  - We would need a separate TS 26.512 CR to add some text at clause 4.11.* and 4.11A.* to specify the data packaging strategies for the two data reporting domains.
  - In the first instance, we could specify that no data packaging strategies are defined in this release and that data reporting client implementations are free to choose whatever packaging strategy they see fit.

Does this satisfy the need for greater clarity, @davidjwbbc?

**Comment by rjb1000** [comment]
Given that this issue affects the provisioning of and UE data reporting to the standalone Data Collection AF (i.e. for exposure of the basic SA2 events to NWDAF), I think changes to both Rel-17 and Rel-18 are justified, even though 5G-MAG Reference Tools is only implementing Rel-18.

- Because this would affect a disjoint set of clauses in TS 26.532 from the other changes requested, this feels like a standalone pair of CRs.
- A matching pair of TS 26.512 CRs= would also be need for Rel-17 and Rel-18.
- TS 26.510 is not impacted.

**Comment by rjb1000** [comment]
Contributions endorsed by SA4 MBS _ad hoc_ meeting:

- TS 26.532
  - Rel-17: **CR0008** "[EVEX] Data packaging strategies" in [S4aI240016](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/Docs/S4aI240016.zip).
  - Rel-18: _To be derived_.
- TS 26.512
  - Rel-17: **CR0065** "[EVEX] Data packaging strategies for 5GMS" in [S4aI240017](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/Docs/S4aI240017.zip).
  - Rel-18: _To be derived_.

**Comment by rjb1000** [comment]
Change Requests contributed to SA4#127-bis-e for agreement:
- TS 26.532
  - Rel-17: **CR0008**r1 "[EVEX] Data packaging strategies" in [S4-240555](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524741).
  - Rel-18: **CR0010** "[EVEX] Data packaging strategies" in [S4-240556](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524742).
- TS 26.512
  - Rel-17: **CR0065**r1 "[EVEX] Data packaging strategies for 5GMS" in [S4-240557](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524743).
  - Rel-18: **CR0067** "[EVEX] Data packaging strategies for 5GMS" in [S4-240558](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524744).

**Comment by rjb1000** [comment]
Change Requests agreed without revision at SA4#127-bis-e:

- TS 26.532
  - Rel-17: **CR0008**r1 "[EVEX] Data packaging strategies" in [S4-240555](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524741).
  - Rel-18: **CR0010** "[EVEX] Data packaging strategies" in [S4-240556](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524742).
- TS 26.512
  - Rel-17: **CR0065**r1 "[EVEX] Data packaging strategies for 5GMS" in [S4-240557](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524743).
  - Rel-18: **CR0067** "[EVEX] Data packaging strategies for 5GMS" in [S4-240558](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524744).
 
These will go to SA#104 for approval in June.

**Comment by rjb1000** [comment]
New specification versions published following approval of CRs at SA#104:
- TS 26.532
  - Rel-17: [V17.3.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.532/26532-h30.zip).
  - Rel-18: [V18.2.1](https://www.3gpp.org/ftp/Specs/archive/26_series/26.532/26532-i21.zip).
- TS 26.512
  - Rel-17: [V17.9.1](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-h91.zip).
  - Rel-18: [18.2.1](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-i21.zip).
