### ISSUE TITLE
TS 26.532: Clarification on eventId read-only status in DataReportingProvisioningSession

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/Standards#113]
# Context

Table 6.3.2.1-1 in TS 26.532 V17.2.0 and V18.1.0 defines the *DataReportingProvisioingSession* object. The _eventId_ property is marked as read-only in Table 6.3.2.1-1. It is unclear how the Data Collection AF knows which event type is intended in order to fill this field in for the response.

In clause B.3, the OpenAPI YAML for the _Ndcaf_DataReportingProvisioning_ service API declares _eventId_ to be a required property of _DataReportingProvisioningSession_ data type, but does not mark it as `readOnly`.

# Clarification question

How should the AF derive this value, or should this field be read-write instead, and set by the ASP's Provisioning AF?

**Comment by rjb1000** [comment]
This one looks like a straightforward bug in TS 26.532 that needs to be corrected in table 6.3.2.1-1.

I suspect the original intent was for the _eventId_ property to be nominated by the Application Service Provider. The absence of the `readOnly` flag in the OpenAPI YAML seems to (correctly) model this, so no API change is needed, I think.

**Comment by rjb1000** [comment]
Given that this issue affects the provisioning of the standalone Data Collection AF (i.e. for exposure of the basic SA2 events to NWDAF), I think changes to both Rel-17 and Rel-18 are justified, even though 5G-MAG Reference Tools is only implementing Rel-18.

The Rel-17 fix could potentially be folded in to TS 26.532 CR0007 that is already addressing #114.

**Comment by rjb1000** [comment]
Change Requests contributed to SA4#127-bis-e for agreement:
* TS 26.532
  * Rel-17 **CR0007**r2 "[EVEX] Essential maintenance" in [S4-240553](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524739).
  * Rel-18 **CR0009** "[EVEX, TEI18] Essential maintenance" in [S4-240554](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524740).

**Comment by rjb1000** [comment]
Change Requests agreed without revision at SA4#127-bis-e:
* TS 26.532
  * Rel-17 **CR0007**r2 "[EVEX] Essential maintenance" in [S4-240553](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524739).
  * Rel-18 **CR0009** "[EVEX, TEI18] Essential maintenance" in [S4-240554](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524740).

These will go to SA#104 for approval in June.

**Comment by rjb1000** [comment]
New specification versions published following approval of CRs at SA#104:
- TS 26.532
  - Rel-17: [V17.3.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.532/26532-h30.zip).
  - Rel-18: [V18.2.1](https://www.3gpp.org/ftp/Specs/archive/26_series/26.532/26532-i21.zip).
