### ISSUE TITLE
TS 26.532: Missing provisioning for `ReportingCondition`s

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/Standards#114]
_This issue pertains to TS 26.532 V17.2.0 and V18.1.0._

# Background

- Table 7.3.2.1-1 defines the *DataReportingSession* object which holds an array of *ReportingCondition* (Table 7.3.2.2-1) objects.

# Description of issue

- Table 6.3.2.2-1 defines the *DataReportingConfiguration* object, but this does not contain provisioning for *ReportingConditions*.
- TS 26.532 v18.1.0 Table 6.3.2.2A-1 defines the *DataReportingConfigurationPatch* object, which also does not contain provisioning for *ReportingConditions*.

Hence, there is no provisioning for *ReportingCondition* objects specified anywhere in TS 26.532.

The *ReportingCondition* objects need to be provisioned somewhere to be provided to reporting clients in the *DataReportingSession* object.

# Suggested Solution

- Move the *ReportingCondition* object type from clause 7.3.2.2 to a new clause 5.4.2.3 since it should be a common data type.
- Add an array of *ReportingCondition* to table 6.3.2.2-1 and table 6.3.2.2A-1.

<div align="center">
  <img width="90%" alt="EVEX stage 3 data model - DataReportingCondition provisioning 2024-02-21" src="https://github.com/5G-MAG/Standards/assets/9865771/5ca689bf-a5e0-4c9e-8575-2c40ea8f165e">
</div>

**Comment by davidjwbbc** [comment]
Added *ReportingCondition* array to the configuration patch as well.

**Comment by rjb1000** [comment]
Change Requests agreed without revision at SA4#127-bis-e:
* TS 26.532
  * Rel-17 **CR0007**r2 "[EVEX] Essential maintenance" in [S4-240553](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524739).
  * Rel-18 **CR0009** "[EVEX, TEI18] Essential maintenance" in [S4-240554](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524740).

These will go to SA#104 for approval in June.

**Comment by rjb1000** [comment]
New specification versions published following approval of CRs at SA#104:
- TS 26.532
  - Rel-17: [V17.3.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.532/26532-h30.zip).
  - Rel-18: [V18.2.1](https://www.3gpp.org/ftp/Specs/archive/26_series/26.532/26532-i21.zip).
