### ISSUE TITLE
TS 26.532: Clarification of Usage values of properties in structured data in Clauses 6 and 7

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/Standards#115]
TS 26.532 v18.1.0 defines several structures in Clauses 6 & 7 which contain Usage values for properties which are not defined in Clause 5.5. Also there are other properties that are marked "RO" in the structure tables in Clauses 6 & 7 which are not flagged as read-only in the OpenAPI YAML in the Annex.

The following table picks out the properties from the structured data objects where the Usage defined does not make sense:

| Table | Object | Property | Usage | Usage meaning | OpenAPI YAML read-only status| Remarks |
| --- | --- | --- | --- | --- | --- | --- |
| 6.3.2.1-1 | DataReporting&ZeroWidthSpace;ProvisioningSession | provisioning&ZeroWidthSpace;SessionId | C: R | Undefined | read-write | Needs to be declared read-only. |
| 6.3.2.1-1 | DataReporting&ZeroWidthSpace;ProvisioningSession | aspId | C: W | Undefined | read-write | Properties can't be declared immutable in OpenAPI, so read–write will have to do. |
| 6.3.2.2-1 | DataReporting&ZeroWidthSpace;Configuration | dataReporting&ZeroWidthSpace;ConfigurationId | C: R | Undefined | read-write | Needs to be declared read-only. |
| 7.3.2.1-1 | DataReporting&ZeroWidthSpace;Session | sessionId | C: — | Not Applicable | read-write | Can't be Not Applicable as it's returned for the create operation |
| 7.3.2.1-1 | DataReporting&ZeroWidthSpace;Session | validUntil | C: — | Not Applicable | read-write | Can't be Not Applicable as it's returned for the create operation |
| 7.3.2.1-1 | DataReporting&ZeroWidthSpace;Session | sampling&ZeroWidthSpace;Rules | C: — | Not Applicable | read-write | Can't be Not Applicable as it's returned for the create operation |
| 7.3.2.1-1 | DataReporting&ZeroWidthSpace;Session | reporting&ZeroWidthSpace;Conditions | C: — | Not Applicable | read-write | Can't be Not Applicable as it's returned for the create operation |
| 7.3.2.1-1 | DataReporting&ZeroWidthSpace;Session | reporting&ZeroWidthSpace;Rules | C: — | Not Applicable | read-write | Can't be Not Applicable as it's returned for the create operation |

What are the correct Usage values and which OpenAPI YAML properties need a "readOnly: true" attribute setting?

**Comment by rjb1000** [comment]
Agree this looks like a bit of a mess and could do with being rationalised.

Given that this issue affects the provisioning and reporting of UE data to the standalone Data Collection AF (i.e. for exposure of the basic SA2 events to NWDAF), I think changes to both Rel-17 and Rel-18 are justified, even though 5G-MAG Reference Tools is only implementing Rel-18.

The Rel-17 fix could potentially be folded in to TS 26.532 CR0007 that is already addressing #114.

**Comment by rjb1000** [comment]
Change Requests contributed to SA4#127-bis-e for agreement:
* TS 26.532
  * Rel-17 **CR0007**r2 "[EVEX] Essential maintenance" in [S4-240553](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524739).
  * Rel-18 **CR0009** "[EVEX, TEI18] Essential maintenance" in [S4-240554](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524740).

**Comment by rjb1000** [comment]
Change Requests agreed without revision at SA4#127-bis-e:
* TS 26.532
  * Rel-17 **CR0007**r2 "[EVEX] Essential maintenance" in [S4-240553](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524739).
  * Rel-18 **CR0009** "[EVEX, TEI18] Essential maintenance" in [S4-240554](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524740).

These will go to SA#104 for approval in June.

**Comment by rjb1000** [comment]
New specification versions published following approval of CRs at SA#104:
- TS 26.532
  - Rel-17: [V17.3.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.532/26532-h30.zip).
  - Rel-18: [V18.2.1](https://www.3gpp.org/ftp/Specs/archive/26_series/26.532/26532-i21.zip).
