### ISSUE TITLE
TS 26.532: Use of "NULL" in DataAggregationFunctionType may cause issues.

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/Standards#117]
# Context

Table 6.3.3.2-1 in TS 26.532 V17.2.0 and V18.1.0 defines the _DataAggregationFunctionType_ enumeration. This enumeration contains a value of "`NULL`".

# Problem

The term `NULL` is used in lots of different computer languages to mean that a value is not defined. However in the case of this enumeration the value is defined, it is just that the meaning is that there is no aggregation function. This can lead to confusion between the absence of the value and the value being defined but indicating no change to the data. It can also clash with parsers trying to interpret the value NULL specially and implementations where NULL also means not defined.

# Suggested Solution

The enumeration should use a term other than `NULL` to avoid confusion. A better term could be `NONE` (there is no aggregation function) or `IDENTITY` (the aggregation function does not change the data).

**Comment by rjb1000** [comment]
Given that this issue affects the provisioning of event exposure in the standalone Data Collection AF (i.e. for exposure of the basic SA2 events to NWDAF), I think changes to both Rel-17 and Rel-18 are justified, even though 5G-MAG Reference Tools is only implementing Rel-18.

The Rel-17 fix could potentially be folded in to TS 26.532 CR0007 that is already addressing #114.

**Comment by rjb1000** [comment]
Change Requests contributed to SA4#127-bis-e for agreement:
* TS 26.532
  * Rel-17 **CR0007**r2 "[EVEX] Essential maintenance" in [S4-240553](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524739).
  * Rel-18 **CR0009** "[EVEX, TEI18] Essential maintenance" in [S4-240554](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524740).

**Comment by rjb1000** [comment]
Change Requests agreed without revision at SA4#127-bis-e:
* TS 26.532
  * Rel-17 **CR0007**r2 "[EVEX] Essential maintenance" in [S4-240553](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524739).
  * Rel-18 **CR0009** "[EVEX, TEI18] Essential maintenance" in [S4-240554](https://portal.3gpp.org/DesktopModules/CRs/CrDetails.aspx?CrId=524740).

These will go to SA#104 for approval in June.

**Comment by rjb1000** [comment]
New specification versions published following approval of CRs at SA#104:
- TS 26.532
  - Rel-17: [V17.3.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.532/26532-h30.zip).
  - Rel-18: [V18.2.1](https://www.3gpp.org/ftp/Specs/archive/26_series/26.532/26532-i21.zip).
