### ISSUE TITLE
TS 26.517: Wrong coding of frequency parameter

### ISSUE THREAD

**Issue by haudiobe** [5G-MAG/Standards#127]
# Context
RAN2 sent an LS to 3GPP SA4 in November 2022 in https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_121_Toulouse/Docs/S4-221229.zip asking that the following two parameters are to be added: "In NR, the frequency parameter is coded as combination of FreqBandIndicatorNR and ARFCN-ValueNR as defined in 3GPP TS 38.331 and TS 38.101." Recently 26.517 was significantly updated in CR 0001 in order to address the removal of XML and only use JSON.

# Problem description
There was an oversight to address the request from RAN2 and only the following parameter is added

radio‌Frequency | array(Uinteger) | M | 1..N | The transmission frequency (expressed in Hertz) associated with the MBS Frequency Selection Area (FSA) Identifier   in the parent service area.
-- | -- | -- | -- | --

# Suggested solution
- Create a CR to 26.517 and address this issue. 
- Send an LS to RAN2 about the updates

**Comment by rjb1000** [comment]
New specification versions published following approval of CRs at SA#104:
- TS 26.517:
  - Rel-17: [V17.6.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.517/26517-h60.zip).
  - Rel-18: [V18.1.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.517/26517-i10.zip).

**Comment by rjb1000** [comment]
Additional CRs agreed at MBS _ad hoc_ meeting to make the new radio parameters optional, since they only apply to MBS Broadcast Session. Also stage-2 alignment CRs to TS 26.502 agreed.

- TS 26.502
  - Rel-17: **CR0032**r1 "Radio parameters alignment" agreed in S4aI240086.
  - Rel-18 mirror: **CR0031** "Radio parameters alignment" agreed in S4aI240080.
- TS 26.517
  - Rel-17: **CR0022** "Make radio parameters optional" agreed in S4aI240092.
  - Rel-18 mirror: **CR0021** "Make radio parameters optional" agreed in S4aI240091.

All four Change Requests will be resubmitted to SA4#129-e for Working Group agreement.

**Comment by rjb1000** [comment]
Change Requests submitted to SA4#129-e:

- TS 26.502
  - Rel-17: **CR0032**r2 "Radio parameters alignment" in S4-241399.
  - Rel-18 mirror: **CR0031**r1 "Radio parameters alignment" in S4-241400.
- TS 26.517
  - Rel-17: **CR0022**r1 "Make radio parameters optional" in S4-241401.
  - Rel-18 mirror: **CR0021**r1 "Make radio parameters optional" in S4aI241402.

**Comment by rjb1000** [comment]
Change Requests submitted to SA4#129-e:

- TS 26.502
  - Rel-17: **CR0032**r2 "Radio parameters alignment" agreed in S4-241399.
  - Rel-18 mirror: **CR0031**r1 "Radio parameters alignment" agreed in S4-241400.
- TS 26.517
  - Rel-17: **CR0022**r1 "Make radio parameters optional" agreed in S4-241401.
  - Rel-18 mirror: **CR0021**r1 "Make radio parameters optional" agreed in S4aI241402.

These go to SA#105 for approval.

**Comment by rjb1000** [comment]
Change Requests approved at SA#105 (Melbourne):
- TS 26.502
  - Rel-17: **CR0032**r2 "Radio parameters alignment" agreed in CR Pack [SP-241110](https://www.3gpp.org/ftp/tsg_sa/TSG_SA/TSGS_105_Melbourne_2024-09/Docs/SP-241110.zip).
  - Rel-18 mirror: **CR0031**r1 "Radio parameters alignment" agreed in CR Pack [SP-241110](https://www.3gpp.org/ftp/tsg_sa/TSG_SA/TSGS_105_Melbourne_2024-09/Docs/SP-241110.zip).
- TS 26.517
  - Rel-17: **CR0022**r1 "Make radio parameters optional" agreed in CR Pack [SP-241109](https://www.3gpp.org/ftp/tsg_sa/TSG_SA/TSGS_105_Melbourne_2024-09/Docs/SP-241109.zip).
  - Rel-18 mirror: **CR0021**r1 "Make radio parameters optional" agreed in CR Pack [SP-241109](https://www.3gpp.org/ftp/tsg_sa/TSG_SA/TSGS_105_Melbourne_2024-09/Docs/SP-241109.zip).

**Comment by rjb1000** [comment]
New specifications published:
- TS 26.502
   - [V17.8.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.502/26502-h80.zip)
   - [V18.2.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.502/26502-i20.zip)
- TS 26.517
   - [V17.7.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.517/26517-h70.zip)
   - [V18.2.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.517/26517-i20.zip)
