### ISSUE TITLE
Finding 5G Broadcast ROM services

### ISSUE THREAD

**Issue by haudiobe** [5G-MAG/Standards#13]
** Step 1: Is your feature request related to a problem? Please describe.**
Different scenarios exist for which other services, applications or web sites use a URL to point to the service, or to a specific resource of a service. There are cases for which finding a service should be possible by
- Using a URL that points to the service or an object delivered on a service
- No unicast is available
- Service acquisition is quick

This particularly applies for ROM and 5G Broadcast services. Examples are
- Pointers from Emergency Alert services to Emergency Broadcast media services
- Fast redirection from unicast to broadcast
- Reference in service guides such as DVB-I

** Step 2: Describe the solution you'd like**
Extend the MBMS URL to include sufficient information to quickly find MBMS and 5G Broadcast User Services. This includes
- Quickly finding the MBMS SA Services
- Identify MBMS User Services in the URL
- Support the search by additional parameters 

For this, a draft CR is proposed for TS 26.347 in [S4-220066](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_117-e/Docs/S4-220066.zip). 

** Step 3: Describe alternatives you've considered**
Alternatives would to scan continuously.

** Step 4: Additional context**
We may need coordination of TMGI management and serviceArea

** Step 5: Choose related standard/project (right side)
see the CR above.

**Comment by dvargasparedero** [comment]
This issue was addressed in TS 26.347 CR0012 ( see clause 8.2.4 of https://www.3gpp.org/ftp/Specs/archive/26_series/26.347/26347-h00.zip)

**Comment by dvargasparedero** [comment]
@haudiobe can this be closed?

**Comment by jordijoangimenez** [comment]
@haudiobe, please check addition in clause 5.5.5 (https://member.5g-mag.com/wg/CD-T/document/779). The addition is quite concise but if needed we can add more explanation.

**Comment by jordijoangimenez** [comment]
Hi @rjb1000,  the confusion comes from me.

When reading 8.1.1 it says "The specification does not define a URL for all Application User Services defined in clause 4.3, but only a subset."

Then I understood that such subset is only for File Delivery Application User Service in 4.3 (according to 8.2.1 An MBMS URL identifies a resource that is made available over MBMS Download Delivery Service using the File Download Application User Service as defined in clause 4.2.3."

**Comment by rjb1000** [comment]
Let's check with @haudiobe.

Even if it only applies to the File Delivery service, the description of the MBMS-URL should be a separate bullet point under list item (1).

**Comment by jordijoangimenez** [comment]
Agree, it deserves its own section. We also need to check if we need to add more info from Section 8 in 26.347 or the current text is enough as a hook to find more in the 3GPP spec.

**Comment by jordijoangimenez** [comment]
New text added making a difference between Services and SA... https://member.5g-mag.com/wg/CD-T/document/779

**Comment by jordijoangimenez** [comment]
Adopted in https://member.5g-mag.com/wg/CD-T/document/779

**Comment by rjb1000** [comment]
Checked and looks good.
