### ISSUE TITLE
TS 26.532 (v18.1.0): DataReportingProvisioning createConfiguration operation under wrong path in YAML

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/Standards#130]
# Description
The YAML OpenAPI description of the createConfiguration API operation in Clause B.3 (TS26532_Ndcaf_DataReportingProvisioning.yaml) places the operation under the path `/sessions/{sessionId}/configurations/{configurationId}`.
Table 6.2.1-1 states that the path for the createConfiguration operation is `/sessions/{sessionId}/configurations`.

The path for this operation in the OpenAPI YAML should not include the `{configurationId}` part.

# Suggested solution
Correct the createConfiguration POST operation by moving it to a new `/sessions/{sessionId}/configurations` path in the OpenAPI YAML.

# Additional Information
This is likely a bug in the Rel-17 spec too.

**Comment by rjb1000** [comment]
I will roll this small additional change into the revision of TS 26.532 **CR0011** that I contribute to SA4#128.

**Comment by rjb1000** [comment]
New specification versions published following approval of CRs at SA#104:
- TS 26.532
  - Rel-17: _Not fixed. Possibly should have been?_
    Rel-18: [V18.2.1](https://www.3gpp.org/ftp/Specs/archive/26_series/26.532/26532-i21.zip).
