### ISSUE TITLE
Information on AV codecs and 5GMS over eMBMS

### ISSUE THREAD

**Issue by jordijoangimenez** [5G-MAG/Standards#14]
** Step 1: Is your feature request related to a problem? Please describe.**
The current spec lacks information on codecs support.

** Step 2: Describe the solution you'd like**
Add information on codecs on a relevant section or clause.

** Step 3: Describe alternatives you've considered**

** Step 4: Additional context**

** Step 5: Choose related standard/project (right side)

**Comment by jordijoangimenez** [comment]
We should harmonize with clause 5.14.2, perhaps mentioning formats supported directly by xMB API and those supported by 5GMS over eMBMS.

**Comment by haudiobe** [comment]
Updated document based on the discussion during the call Oct 13, 2022 is uploaded here.

https://member.5g-mag.com/wg/CD-T/document/827?downloadRevision=1415

**Comment by jordijoangimenez** [comment]
Merged into https://member.5g-mag.com/wg/CD-T/document/779
