### ISSUE TITLE
Lack of support for preselecting a Service Operation Point

### ISSUE THREAD

**Issue by samhurst** [5G-MAG/Standards#141]
# Context
- TS 26.510 specifies the client API for the Media Session Handler at reference points M6/M11 
- TS 26.512 specifies the client API for the Media Access Function (e.g. 5GMS Media Player, RTC Access Function) at reference points M7/M11.

# Problem description
The current client API specifications do not allow the invoker to preselect a Service Operation Point when it has _a priori_ knowledge of this and doesn't (or can't) rely on this information being present in the Media Entry Point resource (e.g. `MPD/ServiceDescription@id` in a DASH MPD).

We are considering the case where the controlling application on the UE has some prior knowledge of what Service Operation Point to select. For example, a media streaming application that knows it is only subscribed to the HD stream and not the UHD stream. This prior knowledge could be hard-coded into the application or obtained via reference point M8.

# Suggested solution
We recommend adding a single Service Operation Point reference as a parameter in these three places:
1. An optional input parameter to the initialize method of the Media Access Function in clause 13.2.3.2 of TS 26.512 (reference point M7). 
1. An optional query parameter to the 3GPP Service URL in clause 12.4 of TS 26.512 (reference point M6).
    * *Because the Service URL request is a generic application's only opportunity to interact with the Media Delivery System.*
    * _estimatedTransferVolume_ also needs to be passed in to support Background Data Transfer.
1. A required input parameter to the `createMediaDeliverySession()` method in clause 11.2.2.1 of TS 26.510 (reference point M6).
    * *This last change is not strictly necessary since it duplicates the functionality of the `activatePolicy()` method, but is a useful convenience that would align this method with the change to the 3GPP Service URL launch above.*

**Comment by ibouazizi** [comment]
In the API clause 11.3, the serviceOperationPointReference parameter is exchanged as part of the activatePolicy method. Isn't this enough for the API? We can of course also add the parameter to the service URL.

**Comment by rjb1000** [comment]
From an API design perspective, I think there is a reasonable argument to keep the input parameters of `createMediaDeliverySession()` aligned with those of the Service URL.

**Comment by rjb1000** [comment]
The basic motivation for selecting a Service Operation Point at the start of a media streaming session is captured in point 5 of cause 4.0.6 in TS 26.501, but it is (intentionally) unspecific about how that is achieved.

@haudiobe's call flow in clause 5.7.6 of TS 26.501 only covers the case where the application chooses a Service Operation Point from the set advertised as Service Descriptions in the DASH MPD. There is no call flow corresponding to the case where an application has _a priori_ knowledge of the Service Operation Point.

For this meeting cycle, we can at least add the missing parameter to the Service URL, which seems broadly agreeable.

We can also pass an _Estimated data transfer volume_ parameter in the Service URL to support the initiation of a Background Data Transfer via a Service URL.

**Comment by rjb1000** [comment]
TDocs reserved for SA4#129-e meeting:

* TS 26.501
  * Rel-16: _Not impacted._
  * Rel-17: _Not impacted._
  * Rel-18: **CR0097** "[5GMS_Ph2] Pre-selection of Service Operation Point in Service URL" in S4-241484.
* TS 26.512
  * Rel-16: _Not impacted._
  * Rel-17: _Not impacted._
  * Rel-18: **CR0078** "[5GMS_Pro_Ph2] Pre-selection of Service Operation Point in Service URL" in S4-241487.

Drafts shared with @haudiobe, @ibouazizi and @samhurst.

**Comment by rjb1000** [comment]
Change Requests agreed at SA4#129-e meeting:

* TS 26.501
  * Rel-16: _Not impacted._
  * Rel-17: _Not impacted._
  * Rel-18: **CR0097** "[5GMS_Ph2] Pre-selection of Service Operation Point in Service URL" in S4-241484.
* TS 26.512
  * Rel-16: _Not impacted._
  * Rel-17: _Not impacted._
  * Rel-18: **CR0078** "[5GMS_Pro_Ph2] Pre-selection of Service Operation Point in Service URL" in S4-241487.

These go to SA1#105 for approval.

**Comment by rjb1000** [comment]
Change Requests approved at SA#105 (Melbourne):

* TS 26.501
  * Rel-16: _Not impacted._
  * Rel-17: _Not impacted._
  * Rel-18: **CR0097** "[5GMS_Ph2] Pre-selection of Service Operation Point in Service URL" in CR Pack [SP-241107](https://www.3gpp.org/ftp/tsg_sa/TSG_SA/TSGS_105_Melbourne_2024-09/Docs/SP-241107.zip).
* TS 26.512
  * Rel-16: _Not impacted._
  * Rel-17: _Not impacted._
  * Rel-18: **CR0078** "[5GMS_Pro_Ph2] Pre-selection of Service Operation Point in Service URL" in CR Pack [SP-241108](https://www.3gpp.org/ftp/tsg_sa/TSG_SA/TSGS_105_Melbourne_2024-09/Docs/SP-241108.zip).

**Comment by rjb1000** [comment]
New specifications published:

* TS 26.501
  * Rel-16: _Not impacted._
  * Rel-17: _Not impacted._
  * Rel-18: [V18.7.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.501/26501-i70.zip).
* TS 26.512
  * Rel-16: _Not impacted._
  * Rel-17: _Not impacted._
  * Rel-18: [V18.3.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-i30.zip)
