### ISSUE TITLE
Emergency Alert over LTE-based 5G Broadcast

### ISSUE THREAD

**Issue by jordijoangimenez** [5G-MAG/Standards#15]
** Step 1: Is your feature request related to a problem? Please describe.**
Include information on how to configure and implement emergency alert services over LTE-based 5G Broadcast

** Step 2: Describe the solution you'd like**
Include a new section or clause covering such services

** Step 3: Describe alternatives you've considered**

** Step 4: Additional context**

** Step 5: Choose related standard/project (right side)

**Comment by dvargasparedero** [comment]
Refer to https://member.5g-mag.com/wg/CD-T/document/828

**Comment by jordijoangimenez** [comment]
@haudiobe provided last version. under discussion in https://member.5g-mag.com/wg/CD-T/document/828

**Comment by jordijoangimenez** [comment]
Integrated version in https://member.5g-mag.com/wg/CD-T/document/779 after changes provided by @haudiobe in https://member.5g-mag.com/wg/CD-T/document/828

**Comment by jordijoangimenez** [comment]
Available in https://member.5g-mag.com/wg/CD-T/document/779
