### ISSUE TITLE
Cardinality of distributionConfigurations.domainNameAlias is ambiguous in Content Hosting Configuration

### ISSUE THREAD

**Issue by rjb1000** [5G-MAG/Standards#16]
# Problem description
TS 26.512 table 7.6.3.1-1 defines the ContentHostingConfiguration resource type.

`distributionConfigurations.domainNameAlias` has a cardinality of 1..1 in the table, but the accompanying text states "The 5GMSd Application Provider **may** assign another FQDN through which media resources are additionally accessible at M4d. ...**If this property is present**..." implying that it is actually optional.

The Open API definition in clause C.3.5 specifies that this is a required property.

This ambiguity should be removed from the specification at the earliest opportunity.

# Discussion
1. Should this property be optional or mandatory?
1. If optional in a Content Hosting provisioning request, should the 5GMSd AS use some default host name? 
   - What if the distribution path on this default host clashes with one already in use by another distribution configuration?

# Suggested solution

Submit a Change Request to SA4 removing the ambiguity. Either:
- Make it mandatory and adjust the confusing description in table 7.6.3.1-1.
- Make it optional by fixing the cardinality column in table 7.6.3.1-1 and making a corresponding fix to the OpenAPI schema in clause C.3.5.

# Additional context
The implementation of the 5GMSd AF needs to know one way or the other!

**Comment by rjb1000** [comment]
Veering towards making `domainNameAlias` optional.

**Comment by davidjwbbc** [comment]
We suspect that this is intended to be optional and that we need to talk to the original author for this field.

**Comment by davidjwbbc** [comment]
@rjb1000 to draft a CR

**Comment by rjb1000** [comment]
3GPP draft Change Request to TS 26.512 Rel-16 [S4aI221386](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/3GPP_SA4_AHOC_MTGs/SA4_MBS/Docs/S4aI221386.zip) opened for initial discussion at today's 3GPP SA4 MBS subworking group ad hoc call. Discussion will continue on 20th October.

(Plan is to create a Rel-17 counterpart later that makes equivalent changes there.)

**Comment by rjb1000** [comment]
Latest draft CR available to 5G-MAG members on Causeway as [CDT0107.3GPP SA4#121 TS26.512 API corrections](https://member.5g-mag.com/wg/CD-T/document/910)

**Comment by rjb1000** [comment]
Formal CRs submitted to SA4#121:
- Rel-16 CR0027 in [S4-221250](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_121_Toulouse/Docs/S4-221250.zip).
- Rel-17 CR0028 in [S4-221251](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_121_Toulouse/Docs/S4-221251.zip).

**Comment by rjb1000** [comment]
The following Change Requests were agreed at SA4#121 Closing Plenary yesterday afternoon:

- TS 26.512:
  - Rel-16: CR0027r2 S4-221605.
  - Rel-17: CR0028r2 S4-221606.

**Comment by rjb1000** [comment]
Change Requests approved at SA#98-e:
- Rel-16: **CR0027r2** in [SP-221042](https://portal.3gpp.org/ngppapp/CreateTdoc.aspx?mode=view&contributionId=1394078).
- Rel-17: **CR0028r2** in [SP-221043](https://portal.3gpp.org/ngppapp/CreateTdoc.aspx?mode=view&contributionId=1394079).

**Comment by rjb1000** [comment]
New specifications published:
- [TS 26.512 V16.8.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-g80.zip).
- [TS 26.512 V17.3.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-h30.zip).
