### ISSUE TITLE
Cardinality of ingestConfiguration.path is incorrect in Content Hosting Configuration

### ISSUE THREAD

**Issue by rjb1000** [5G-MAG/Standards#18]
# Problem description
The Content Hosting Configuration property `ingestConfiguration.path` is marked with cardinality 1..1 in table 7.6.3.1-1.

The accompanying description implies it is only used in the case of push-based ingest into the 5GMSd AS. And it is nominated by the 5GMS AF in this case:

> The relative path which will be used to address the media resources at interface M2d.
> This path is provided by the 5GMSd AF in the case of Push-based ingest.

The OpenAPI schema definition in clause C.3.1 does not mark this property (or, in fact, any properties in `ingestConfiguration`) as required.

# Suggested solution

In the specification of the `ingestConfiguration.path` property in table 7.6.3.1-1:
1. Correct the _Cardinality_ to be 0..1.
1. Clarify in the _Description_ that the property is never present for pull-based ingest.
1. Specify in the _Description_ that it is an error to provide this property in an M1d request. It is only ever present in an M1d response generated by the 5GMSd AF.

In addition, consider renaming the property `ingestConfiguration.pushPath` to make its limited purpose more self-describing.

# Additional context
This issue was discovered when implementing the 5GMSd AF.

**Comment by davidjwbbc** [comment]
Fix the cardinality in table 7.6.3.1-1 to show this as optional.

@rjb1000 will raise a CR

**Comment by rjb1000** [comment]
3GPP draft Change Request to TS 26.512 Rel-16 [S4aI221386](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/3GPP_SA4_AHOC_MTGs/SA4_MBS/Docs/S4aI221386.zip) opened for initial discussion at today's 3GPP SA4 MBS subworking group ad hoc call. Discussion will continue on 20th October.

(Plan is to create a Rel-17 counterpart later that makes equivalent changes there.)

**Comment by rjb1000** [comment]
Latest draft CRs available to 5G-MAG members on Causeway as [CDT0107.3GPP SA4#121 TS26.512 API corrections](https://member.5g-mag.com/wg/CD-T/document/910).

**Comment by rjb1000** [comment]
Formal CRs submitted to SA4#121:
- Rel-16 CR0027 in [S4-221250](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_121_Toulouse/Docs/S4-221250.zip).
- Rel-17 CR0028 in [S4-221251](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_121_Toulouse/Docs/S4-221251.zip).

**Comment by rjb1000** [comment]
The following Change Requests were agreed at SA4#121 Closing Plenary yesterday afternoon:

- TS 26.512:
  - Rel-16: CR0027r2 S4-221605.
  - Rel-17: CR0028r2 S4-221606.

**Comment by rjb1000** [comment]
Change Requests approved at SA#98-e:
- Rel-16: **CR0027r2** in [SP-221042](https://portal.3gpp.org/ngppapp/CreateTdoc.aspx?mode=view&contributionId=1394078).
- Rel-17: **CR0028r2** in [SP-221043](https://portal.3gpp.org/ngppapp/CreateTdoc.aspx?mode=view&contributionId=1394079).

**Comment by rjb1000** [comment]
New specifications published:
- [TS 26.512 V16.8.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-g80.zip).
- [TS 26.512 V17.3.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-h30.zip).
