### ISSUE TITLE
Use of path part of URL in IngestConfiguration.entryPoint for pull ingest

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/Standards#19]
### Problem Description
In TS 26.512:
- Table 7.6.3.1-1 states that for pull content the _IngestConfiguration.entryPoint_ is the location from which content is pulled and is used as a base URL for requests for the pull ingest.
- Section 8.2 states that for pull ingest "The _IngestConfiguration.entryPoint_ shall not contain a path part."
- Section 8.2 also states that pull ingest request URL is made up from a concatenation of the _IngestConfiguration.entryPoint_ and the _mappedPath_, and does not include the _IngestConfiguration.path_.

The limitation in section 8.2 seems to go against the spirit of using the _IngestConfiguration.entryPoint_ as a base URL by forbidding the use of the path part of the URL. By also excluding the _IngestConfiguration.path_ from the method of creating the pull ingest URL, this forces any path required at the _IngestConfiguration.entryPoint_ to be inserted using the Regex backed _DistributionConfigurations.PathRewriteRules_, when a computationally less expensive concatenation would have sufficed.

There should also be clarification about what is meant by "base URL" in table 7.6.3.1-1 as the simple meaning of it being a base prefix, as suggested by the description in section 8.2, is different from the interpretation and usage in URL resolution of a base URI according to IETF RFC3986.

### Discussion
Should the restriction on the path part of the URL be dropped in Section 8.2 to allow simpler configurations to be possible when creating a Content Hosting Configuration?

Is the intention of "base URL" in table 7.6.3.1-1 to resolve URLs according to the usage of base URIs as stated in IETF RFC 3986?

**Comment by davidjwbbc** [comment]
Proposal is to delete the sentence from 8.2 ("The IngestConfiguration.entryPoint shall not contain a path part.") to relax the rules for the entryPoint field.

@rjb1000 to raise a draft CR to stimulate discussion in SA4.

**Comment by rjb1000** [comment]
3GPP draft Change Request to TS 26.512 Rel-16 [S4aI221386](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/3GPP_SA4_AHOC_MTGs/SA4_MBS/Docs/S4aI221386.zip) opened for initial discussion at today's 3GPP SA4 MBS subworking group ad hoc call. Discussion will continue on 20th October.

(Plan is to create a Rel-17 counterpart later that makes equivalent changes there.)

**Comment by rjb1000** [comment]
Latest draft CR proposes deprecating the confusingly named `IngestConfiguration.entryPoint` and `IngestConfiguration.path` in favour of `IngestConfiguration.baseURL`.

To compensate, a `ContentHostingConfiguration.entryPointPath` is added, applicable to both ingest and distribution base URLs.

**Comment by rjb1000** [comment]
Latest draft CRs available to 5G-MAG members on Causeway as [CDT0107.3GPP SA4#121 TS26.512 API corrections](https://member.5g-mag.com/wg/CD-T/document/910).

**Comment by rjb1000** [comment]
Formal CRs submitted to SA4#121:
- Rel-16 CR0027 in [S4-221250](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_121_Toulouse/Docs/S4-221250.zip).
- Rel-17 CR0028 in [S4-221251](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_121_Toulouse/Docs/S4-221251.zip).

**Comment by rjb1000** [comment]
The following Change Requests were agreed at SA4#121 Closing Plenary yesterday afternoon:

- TS 26.512:
  - Rel-16: CR0027r2 S4-221605.
  - Rel-17: CR0028r2 S4-221606.

**Comment by rjb1000** [comment]
New specifications published:
- [TS 26.512 V16.8.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-g80.zip).
- [TS 26.512 V17.3.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-h30.zip).
