### ISSUE TITLE
Simultaneous service reception

### ISSUE THREAD

**Issue by haudiobe** [5G-MAG/Standards#20]
# Description
Receivers are restricted in simultaneous reception of TMGIs.

# Suggested solution
Add a requirement that 
- 32 simultaneous TMGIs reception
- 4 simultaneous user services
on a single carrier shall be supported.

Services shall be offered in a way that receivers fulfilling the requirements can properly operate.

# Additional context
If not available, it will be confusing.

**Comment by jordijoangimenez** [comment]
Add a recommendation (implementation guideline) for the receiver and service provider to support ("more than one" or "up to four") TMGIs simultaneously. Add an example about e.g. Main service + EPG + SA + PiP...

**Comment by haudiobe** [comment]
A proposed CR is uploaded here: https://member.5g-mag.com/wg/CD-T/document/897?downloadRevision=1431

**Comment by jordijoangimenez** [comment]
Adopted in https://member.5g-mag.com/wg/CD-T/document/779

**Comment by rjb1000** [comment]
Reviewed in draft v1.1.9rm. Broadly fine. Will propose some minor editorial updates.

I wonder if the material might find a better home in clause 7.4 (requirements on the MBMS Client), though.

**Comment by jordijoangimenez** [comment]
thanks your checking, Richard. I think it's in 12.3 because we said it was more for recommendation/implementation guideline?

**Comment by rjb1000** [comment]
Sorry for the confusion: the implementation guidelines are correctly in clause 12.3.

It's the material in clause 7.2 that might find a more suitable home in clause 7.4.

**Comment by jordijoangimenez** [comment]
Moved to 7.4 in https://member.5g-mag.com/wg/CD-T/document/779 (1.1.10)

**Comment by rjb1000** [comment]
Move to clause 7.4 looks good. Thanks.

**Comment by jordijoangimenez** [comment]
Ready to be closed.

**Comment by jordijoangimenez** [comment]
We need an update wrt TS 26.346 (C.17,C.18 and C.19). Include an example of an SA with the parameters.

https://github.com/5G-MAG/Standards/issues/26

ROM SACH to TS 26.346 (S4-221478, S4-221479) and TS 26.347 in S4-221481
https://www.3gpp.org/ftp/tsg_sa/WG4_CODEC/TSGS4_121_Toulouse/Docs/S4-221478.zip
