### ISSUE TITLE
Clarifications on the use of ContentHostingConfiguration in different hosting scenarios

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/Standards#21]
# Problem description
While trying to implement a 5GMS AS I've been looking at the 5GMS Release 17 specifications. I've noticed that the interactions expected between the Application Provider and the 5GMS AF, for different content hosting scenarios, doesn't appear to be documented.

From the AP's point of view there appears to be no description of what the AP needs to provide and how to convey to the AF the information needed to provide the hosting or proxying requirements.

From the AF's point of view there is no description of what it is expected to provide to the AP for different ContentHostingConfigurations.

I've considered a few scenarios for AP/AF interaction while considering how the ContentHostingConfiguration can be used.

### A. Simple caching reverse proxy for a single media asset
In this scenario the AP has a media origin server with the desired media objects for the asset already created (e.g. MPDs, HLS m4u files, media segments in various resolutions and bitrates). The AF and AS are configured to provide a caching reverse proxy to the origin server with the AF advertising the asset entry point via the ServiceAccessInformation on M5d.

In this case the AP will need to provide the URL to the root of the media asset, for pull ingest, along with the relative path, from the media asset root, of the asset entry point (e.g. the location of the MPD) for advertisement by the AF on M5d as a mediaPlayerEntry in the ServiceAccessInformation.

This gives the AP full control over the quality and bit rate of the media representations on offer for their content.

#### ContentHostingConfiguration
Field | Contents | Example
 --- | --- | --- 
`IngestConfiguration.protocol` | _urn:3gpp:5gms:content-protocol:http-pull-ingest_ | 
`IngestConfiguration.entryPoint` | Location of origin server | https://origin.example.com/
`DistributionConfigurations[0].PathRewriteRules[0].requestPattern` | Regex to match distribution root | ^/m4d/
`DistributionConfigurations[0].PathRewriteRules[0].mappedPath` | Root path on origin | /dash-asset-1234/
? | Media asset entry point path | manifests/dash-asset-1234-4s-HD.mpd

### B. Simple caching reverse proxy for a set of media assets from the same origin
This is similar to scenario A except that the AP does not provide an asset entry point (e.g. path to the MPD) and so no mediaPlayerEntry is advertised in the ServiceAccessInformation. All media entry point URLs (e.g. MPD URLs that can be accessed via M4d) are provided via the M8d interface to the 5GMS-Aware Application from the AP.

This allows the AP to be very dynamic with what media assets are advertised to which 5GMS clients and also retains the control and distribution efficiencies mentioned above.

#### ContentHostingConfiguration as provided by AP
Field | Contents | Example
 --- | --- | --- 
`IngestConfiguration.protocol` | _urn:3gpp:5gms:content-protocol:http-pull-ingest_ | 
`IngestConfiguration.entryPoint` | Location of origin server | https://origin.example.com/
`DistributionConfigurations[0].PathRewriteRules[0].requestPattern` | Regex to match distribution root | ^/m4d/
`DistributionConfigurations[0].PathRewriteRules[0].mappedPath` | Root path on origin | /
</table>

### C. Simple hosting for a single media asset
In this scenario the AP has media assets it wishes to push to a distribution server. The AF and AS are configured to provide hosting with a push ingest point. The AF will advertise the media entry point via the ServiceAccessInformation on M5d.

Initially the AP will only need to provide the relative entry point of the media asset (e.g. path to the MPD relative to the media asset root), within the file structure it intends to push, for advertisement by the AF on M5d in the ServiceAccessInformation. The AF will respond with the ingest service details so that the AP can start to populate the hosting service. The ServiceAccessInformation will only be published by the AF once the AP has finished pushing media files, so a signal from the AP to the AF when the asset is available will need to happen.

This gives the AP full control over the quality and bit rate of media representations on offer for their content and is also more efficient when the source material is in high resolution raw video formats.

#### ContentHostingConfiguration as provided by AP
Field | Contents | Example
 --- | --- | --- 
`IngestConfiguration.protocol` | _urn:3gpp:5gms:content-protocol:dash-if-ingest_ | 
? | Media asset entry point path | manifests/dash-asset-1234-4s-HD.mpd

### D. Simple hosting for a single live service
Same as for scenario C except that media object expiry will need to be set to delete old live object (e.g. deletion 2 hours after push), and the ServiceAccessInformation can be published by the AF as soon as the first set of live media segments is pushed from the AP.

This gives the AP full control over the quality and bit rate of media representations on offer for their content and also gives control over the availability of those media segments.

#### ContentHostingConfiguration as provided by AP
Field | Contents | Example
 --- | --- | --- 
`IngestConfiguration.protocol` | _urn:3gpp:5gms:content-protocol:dash-if-ingest_ | 
`DistributionConfigurations[0].CachingConfigurations[0].urlPatternFilter` | Regex pattern to match hosted files | .*\.m4s
`DistributionConfigurations[0].CachingConfigurations[0].maxAge` | Maximum age of pushed media object | 7200
? | Media asset entry point path | manifests/dash-asset-1234-4s-HD.mpd

### E. Processed content hosting of single media asset
For this scenario the AP only has a single media file they wish to be hosted in one or more streaming formats. The AP requests ContentPreparationTemplates during its provisioning phase for the streaming types it would like (e.g. DASH and HLS). Multiple DistributionConfigurations are provided, each referencing a different ContentPreparationTemplateId.

The AF provides the ingest service details and the AP pushes its single media file to the ingest service. The AF arranges for the transformation of the ingested media file to provide the relevant streaming objects for the content type at the distribution AS's and publishes the entry point URL as a mediaPlayerEntry in the ServiceAccessInformation on M5d once the ingest and transformation are complete.

The AP delegates control over the quality and available bit rates of the produced streams to the AF. The AP would have to ensure that the ingest material is of sufficient resolution and quality for the transformation processes provided by the AF.

#### ContentHostingConfiguration as provided by AP
Field | Contents | Example
 --- | --- | --- 
`IngestConfiguration.protocol` | _urn:3gpp:5gms:content-protocol:dash-if-ingest_ | 
`DistributionConfigurations[0].contentPreparationTemplateId` | ContentPreparationTemplate ResourceID of the first streaming type | 1
`DistributionConfigurations[1].contentPreparationTemplateId` | ContentPreparationTemplate ResourceID of the second streaming type | 2

---

There appears to be no mapping at present for the media entry point (e.g. MPD URL) so that it can be published in the ServiceAccessInformation.StreamingAccess.mediaPlayerEntry field, which affects scenarios A to D.

## Questions arising
- DistributionConfigurations is an array, so what does it mean if simple pull-ingest is requested (scenario A) with more than one DistributionConfiguration? Could you have a distribution for HLS separate from the distribution for DASH but both referencing the same media origin and so be configured in the same ContentHostingConfiguration? If so how would you distinguish which distribution configuration is which, especially when the domainNameAlias fields are used? Or would it not matter which was which until a media entry point is assigned? Should this be allowed?
- The DistributionConfigurations, after the AF has filled in canonicalDomainName fields, point to the host FQDN for distribution host, but what if a non-standard port is required? How is the distribution scheme (e.g. ftp, http, https) signalled? If you configure a certificate for SSL is that distribution configuration just for https or does it also provide an http endpoint too (and maybe an ftp endpoint too)?
- <strike>The ContentPreparationTemplates just say they are MIME type dependant, but where is the MIME type signalled? Are there any standard definitions of this template structure, for popular MIME types like application/dash+xml, already defined?</strike>

**Comment by rjb1000** [comment]
Just to note that Content Preparation Templates are underspecified in Release 16 and Release 17. It's therefore not really possible to realise Scenario E in a standardised way right now. So it's unlikely that we will attempt a reference implementation any time soon.

Still, it's good to consider how the pieces of the jigsaw fit together, and this is good feedback for the specification authors.

**Comment by davidjwbbc** [comment]
Separated ContentHostingConfiguration table and added entries to each scenario in the issue description

**Comment by davidjwbbc** [comment]
Found the answer to the ContentPreparationTemplate MIME type question, it is mentioned briefly in section 4.3.5.2 as using the Content-Type header to convey the MIME type of the ContentPreparationTemplate itself. So the MIME type refers to that of the template rather than the prepared media type.

**Comment by rjb1000** [comment]
Presentation about the media entry point contributed to 3GPP SA4 MBS subworking group as [S4aI221393](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/3GPP_SA4_AHOC_MTGs/SA4_MBS/Docs/S4aI221393.zip).

Discussion postponed until 20th October due to lack of meeting time today.

**Comment by jordijoangimenez** [comment]
Should we update the milestone or leave it undefined?

**Comment by rjb1000** [comment]
@davidjwbbc: Have the issues you described been addressed in TS 26.512 V17.3.0?

If so, please close this issue with an appropriate summary comment.

**Comment by davidjwbbc** [comment]
I think a lot of the issues have been addressed by the recent changes to TS 26.512 v17.3.0 and from the discussions with SA4 members. The issues with multiple distribution configurations were mentioned in the meeting with the conclusion being that in most cases only one or two configurations would ever be used.

I think it would be useful to document somewhere descriptions of configuration for intended use cases (simple pull, simple push, content preparation push, etc.), what the AP should provide in that case, what the AF will provision and what combinations are undefined or prohibited. This information is not obvious from the specifications and would be very useful to APs and those writing AF software. It would be useful to get the original API designers in SA4 to document the use cases they had in mind when writing the original specification and how those use cases fit in with the M1 API.

I think that, as far as this issue is concerned, it has been answered and can be closed.

**Comment by rjb1000** [comment]
> I think it would be useful to document somewhere descriptions of configuration for intended use cases (simple pull, simple push, content preparation push, etc.), what the AP should provide in that case, what the AF will provision and what combinations are undefined or prohibited. This information is not obvious from the specifications and would be very useful to APs and those writing AF software. It would be useful to get the original API designers in SA4 to document the use cases they had in mind when writing the original specification and how those use cases fit in with the M1 API.

I agree that some examples of M1 Content Hosting Configurations would be helpful to implementers. This could form an informative annex to TS 26.512.

Please could you create a new issue linked back to this one to capture that, @davidjwbbc?
