### ISSUE TITLE
Reference Update to ETSI Rel-17 specs

### ISSUE THREAD

**Issue by haudiobe** [5G-MAG/Standards#23]
# Problem description
TS 103 720 v1.1.1 refers to Rel-16 ETSI Specs

# Suggested solution
Update to Rel-17 specs

# Additional context
In the references, make all spec references Rel-17

**Comment by jordijoangimenez** [comment]
I believe this is done in https://member.5g-mag.com/wg/CD-T/document/779

**Comment by jordijoangimenez** [comment]
Adopted in https://member.5g-mag.com/wg/CD-T/document/779
