### ISSUE TITLE
Support of UHF band in 3GPP Release 18

### ISSUE THREAD

**Issue by jordijoangimenez** [5G-MAG/Standards#24]
# Problem description
The document does not contain information about normative work in 3GPP Release 18 to support the use of the UHF band for LTE-based 5G Broadcast ([LTE_terr_bcast_bands_part2](https://www.3gpp.org/DynaReport/WiSpec--920071.htm))

# Suggested solution description
Add information into relevant section including section 8.

**Comment by rjb1000** [comment]
The current activity to revise ETSI TS 103 720 is targeting alignment with 3GPP Rel-17.

This issue can therefore be assigned to a future milestone.
