### ISSUE TITLE
IP Multicast Address and UDP destination ports for ROM service 

### ISSUE THREAD

**Issue by jordijoangimenez** [5G-MAG/Standards#25]
# Description
TS 103 720 does not currently reference mandatory IP addresses and UDP destination ports to be used for the Service Announcement service needed to support receiver bootstrapping in Receive-Only Mode.

# Suggested solution
- Amend TS 26.346 annexes C.17, C.18 and C.19 to make the necessary normative statements - see separate issue #26.
- Reference these statements from TS 103 720 clause 5.5.3.

**Comment by jordijoangimenez** [comment]
Added in https://member.5g-mag.com/wg/CD-T/documentRevision/create/779 (1.1.10)

**Comment by rjb1000** [comment]
New bullet in clause 5.5.3 looks good, but I found a few minor editorial nits.

**Comment by jordijoangimenez** [comment]
Ready to be closed.

**Comment by jordijoangimenez** [comment]
We need an update wrt TS 26.346 (C.17,C.18 and C.19). Include an example of an SA with the parameters.

https://github.com/5G-MAG/Standards/issues/26

ROM SACH to TS 26.346 (S4-221478, S4-221479) and TS 26.347 in S4-221481
https://www.3gpp.org/ftp/tsg_sa/WG4_CODEC/TSGS4_121_Toulouse/Docs/S4-221478.zip

**Comment by jordijoangimenez** [comment]
Please check [CDT0092.ETSI TS 103 720 V1.1.12rm.docx](https://member.5g-mag.com/wg/CD-T/document/779)
No example though,

**Comment by jordijoangimenez** [comment]
Included in version 1.1.13. https://member.5g-mag.com/wg/CD-T/document/779

**Comment by rjb1000** [comment]
Note that new versions of TS 26.346 and TS 26.347 have now been published (see [this comment](https://github.com/5G-MAG/Standards/issues/26#issuecomment-1375379736) on 5G-MAG/Standards#26).

These now explicitly specify the IP addresses and UDP destination port to be used for the Service Announcement in Receive-Only Mode.
