### ISSUE TITLE
IP Multicast Address and UDP destination ports for ROM service

### ISSUE THREAD

**Issue by jordijoangimenez** [5G-MAG/Standards#26]
# Description
TS 26.346 does not currently specify the multicast IP address and UDP destination port of a Service Announcement service that indicates the availability of ROM service(s).

# Suggested solution
Add relevant IANA registrations to the following clauses in TS 26.346:
- C.17: IPv4 multicast group address.
- C.18: IPv6 multicast group address.
- C.19: UDP destination port number.

**Comment by haudiobe** [comment]
Feedback on Charles on the question if there is any progress

No I've not done so. I will pick this up when I return to SD end of October.

I would think getting the assignment might take time. Would simply stating in the next version of the ETSI spec that the addresses are undergoing application sufficient?

Charles

**Comment by jordijoangimenez** [comment]
Thanks!

A short term solution is to reference annexes C.17, C.18, C.19 of TS 26.346 in the ETSI spec. Eg.“Additional details including multicast IP address… xxx …are to be defined in clauses C.17, C.18 and C.19 of ETSI TS 126 346…” or something like that.

Of course having the numbers in the ETSI spec is ideal but this should be done in a future version.

**Comment by rjb1000** [comment]
Question: Is it necessary to reserve a Source-Specific Multicast group destination address for the ROM Service Announcement Service? Given that the MBMS Client listens promiscuously in Receive-Only Mode, would an Any-Source Multicast group address not be adequate for this purpose?

For example, Multicast DNS (a.k.a. Apple Bonjour) uses 224.0.0.251 (from the [Local Network Control Block](https://www.iana.org/assignments/multicast-addresses/multicast-addresses.xhtml#multicast-addresses-1)) or ff02::fb as its destination group address. Could 3GPP request a similar registration from IANA for the ROM Service Announcement Service?

**Comment by rjb1000** [comment]
Note that an **IPv6** address needs to be reserved in clause C.18 in addition to the IPv4 address in clause C.17.

**Comment by rjb1000** [comment]
IANA registrations were requested last week by Charles Lo of Qualcomm.

So far the following values have been allocated:
- IPv4:  224.0.0.120 "3GPP MBMS SACH" (in [Local Network Control block](https://www.iana.org/assignments/multicast-addresses/multicast-addresses.xhtml#multicast-addresses-1))
- IPv6:  FF0X:0:0:0:0:0:0:177 "3GPP MBMS SACH" (in [Variable Scope Multicast block](https://www.iana.org/assignments/ipv6-multicast-addresses/ipv6-multicast-addresses.xhtml#variable))

UDP port assignment is still pending.

Formal 3GPP Change Requests to record these values in TS 26.346 are in preparation.

**Comment by rjb1000** [comment]
Summary of current status contributed to SA4#121 by Charles Lo as a discussion paper [S4-221282](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_121_Toulouse/Docs/S4-221282.zip).

Formal Change Requests contributed to SA4#121 by Charles Lo:
- Rel-14: S4-221283 (withdrawn).
- Rel-15: S4-221284 (withdrawn).
- Rel-16: [S4-221285](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_121_Toulouse/Docs/S4-221285.zip).
- Rel-17: [S4-221286](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_121_Toulouse/Docs/S4-221286.zip).

**Comment by rjb1000** [comment]
The following Change Requests were agreed at SA4#121 Closing Plenary yesterday afternoon:
- CR 26.346:
  - Rel-16: CR0666r1 S4-221478.
  - Rel-17: CR0667r1 S4-221479
- CR 26.347:
  - Rel-16: _Not applicable._
  - Rel-17: CR0015 S4-221481

**Comment by rjb1000** [comment]
Change Requests approved at SA#98-e:
- CR 26.346:
  - Rel-16: **CR0666r1** [SP-221041](https://portal.3gpp.org/ngppapp/CreateTdoc.aspx?mode=view&contributionId=1394077).
  - Rel-17: **CR0667r1** [SP-221041](https://portal.3gpp.org/ngppapp/CreateTdoc.aspx?mode=view&contributionId=1394077).
- CR 26.347:
  - Rel-16: _Not applicable_.
  - Rel-17: **CR0015** [SP-221046](https://portal.3gpp.org/ngppapp/CreateTdoc.aspx?mode=view&contributionId=1394083).

**Comment by rjb1000** [comment]
New specifications published:
- [TS 26.346 V16.11.1](https://www.3gpp.org/ftp/Specs/archive/26_series/26.346/26346-gb1.zip).
- [TS 26.346 V17.2.1](https://www.3gpp.org/ftp/Specs/archive/26_series/26.346/26346-h21.zip).
- [TS 26.347 V17.2.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.347/26347-h20.zip).
