### ISSUE TITLE
Inconsistency for parameter name requestPathPattern

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/Standards#27]
# Problem description
3GPP TS 26.512 defines multiple parameters to be used within `PathRewriteRules`. The naming of the `requestPathPattern` parameter is inconsistent:

- Table 7.6.3.1-1 defines `requestPathPattern`
- Annex C3.5 M1_ContentHostingProvisioning API defines `requestPattern`

# Suggested solution
Agree on a name for the parameter mentioned above. Probably `requestPattern` in Annex C3.5 should be renamed to  `requestPathPattern`

**Comment by rjb1000** [comment]
Thanks for spotting, @dsilhavy. This seems to be a straightforward error. I agree with the suggested solution and will include it in the next revision of my draft CR.

**Comment by rjb1000** [comment]
Latest draft CRs available to 5G-MAG members on Causeway as [CDT0107.3GPP SA4#121 TS26.512 API corrections](https://member.5g-mag.com/wg/CD-T/document/910).

**Comment by rjb1000** [comment]
Formal CRs submitted to SA4#121:
- Rel-16 CR0027 in [S4-221250](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_121_Toulouse/Docs/S4-221250.zip).
- Rel-17 CR0028 in [S4-221251](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_121_Toulouse/Docs/S4-221251.zip).

**Comment by rjb1000** [comment]
The following Change Requests were agreed at SA4#121 Closing Plenary yesterday afternoon:

- TS 26.512:
  - Rel-16: CR0027r2 S4-221605.
  - Rel-17: CR0028r2 S4-221606.

**Comment by rjb1000** [comment]
Change Requests approved at SA#98-e:
- Rel-16: **CR0027r2** in [SP-221042](https://portal.3gpp.org/ngppapp/CreateTdoc.aspx?mode=view&contributionId=1394078).
- Rel-17: **CR0028r2** in [SP-221043](https://portal.3gpp.org/ngppapp/CreateTdoc.aspx?mode=view&contributionId=1394079).

**Comment by rjb1000** [comment]
New specifications published:
- [TS 26.512 V16.8.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-g80.zip).
- [TS 26.512 V17.3.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-h30.zip).
