### ISSUE TITLE
ContentHostingConfiguration.distributionConfigurations.supplementaryDistributionNetworks inconsistencies.

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/Standards#28]
# Description
From TS 26.512:

1. Table 7.6.3.1-1 states that the `distributionConfigurations.supplementaryDistributionNetworks` field is a "Array(Map(DistributionNetworkType -> DistributionMode)", this has an uneven number of brackets. The text suggests that this is a mappings list, so "Array(" probably should not be there.
2. Annex C.3.5 defines `distributionConfigurations.supplementaryDistributionNetworks` as an object with a "default" property whose value is a `DistributionNetworkType` and any other property whose value is a `DistributionMode` type. This is contradictory to the suggested structure in table 7.6.3.1-1.

The table suggests that this structure should look something like:
```
{
  "NETWORK_EMBMS": "MODE_HYBRID",
  "FUTURE_NETWORK_TYPE": "MODE_EXCLUSIVE"
}
```

However the OpenAPI in C.3.5 suggests that it would look like (where "default" is a mandatory property):
```
{
   "default": "NETWORK_EMBMS",
   "anything_i_want": "MODE_HYBRID"
}
```
I suspect that the first interpretation, from the table, is the correct one. Unfortunately this cannot be explicitly specified in OpenAPI as the type of the object property keys cannot be defined, they have to be a plain `string`. If this structure is wanted, then the only option is to document what the key type should be in the object description text.

_(From discussion on this issue)_
The alternative, in order to strongly type the two values, is to change this to an array of objects which have two mandatory fields, one for the `distributionNetworkType` and one for the `distributionMode`.

# Suggested solution
1. Change the entry for `distributionConfigurations.supplementaryDistributionNetworks` in table 7.6.3.1-1 to say "Array(Object)" for the Data Type.
2. Add two extra rows in Table 7.6.3.1-1 after `distributionConfigurations.supplementaryDistributionNetworks`:
<table>
<tr><td>&nbsp;&nbsp;&nbsp;&nbsp;<em>distributionNetworkType</em></td><td><code>DistributionNetworkType</code></td><td>1..1</td><td>Specifies the distribution network type for this mapping. Must be unique within this <em>supplementaryDistributionNetworks</em> array.</td></tr>
<tr><td>&nbsp;&nbsp;&nbsp;&nbsp;<em>distributionMode</em></td><td><code>DistributionMode</code></td><td>1..1</td><td>Specifies the distribution mode to use with the <em>distributionNetworkType</em>.</td></tr>
</table>
3. Change the YAML in C.3.5 for <code>TS26512_M1_ContentHostingProvisioning.yaml#components/schemas/DistributionConfiguration/supplementaryDistributionNetworks</code> to:
<pre>
supplementaryDistributionNetworks:
    type: array
    items:
        type: object
        properties:
            distributionNetworkType:
                $ref: '#/components/schemas/DistributionNetworkType'
            distributionMode:
                $ref: '#/components/schemas/DistributionMode'
        required:
          - distributionNetworkType
          - distributionMode
</pre>

**Comment by rjb1000** [comment]
(Note that this issue does not affect Rel-16: it is a feature of Rel-17 onwards.)

**Comment by rjb1000** [comment]
The design intent here is a dictionary (associative array, hash map) with a fixed repertoire of keys.

https://swagger.io/docs/specification/data-models/dictionaries/

**Comment by rjb1000** [comment]
If the index of the associative array cannot be strongly typed in OpenAPI, how about a simple array of objects that have two members: `distributionNetworkType` and `distributionMode`?

**Comment by davidjwbbc** [comment]
The array of objects with a pair of values would be:
```
supplementaryDistributionNetworks:
    type: array
    items:
        type: object
        properties:
            distributionNetworkType:
                $ref: '#/components/schemas/DistributionNetworkType'
            distributionMode:
                $ref: '#/components/schemas/DistributionMode'
        required:
          - distributionNetworkType
          - distributionMode
```

**Comment by rjb1000** [comment]
Yes, that's precisely what I had in mind, @davidjwbbc.

Thanks for saving me the trouble!

**Comment by rjb1000** [comment]
Latest draft CR for Rel-17 available to 5G-MAG members on Causeway as [CDT0107.3GPP SA4#121 TS26.512 API corrections](https://member.5g-mag.com/wg/CD-T/document/910).

**Comment by rjb1000** [comment]
Formal CRs submitted to SA4#121:
- _(This feature did not exist in Rel-16.)_
- Rel-17 CR0028 in [S4-221251](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_121_Toulouse/Docs/S4-221251.zip).

**Comment by rjb1000** [comment]
The following Change Requests were agreed at SA4#121 Closing Plenary yesterday afternoon:

- TS 26.512:
  - Rel-16: _(Not applicable.)_
  - Rel-17: CR0028r2 S4-221606.

**Comment by rjb1000** [comment]
Change Request approved at SA#98-e:
- Rel-17: **CR0028r2** in [SP-221043](https://portal.3gpp.org/ngppapp/CreateTdoc.aspx?mode=view&contributionId=1394079).

**Comment by rjb1000** [comment]
New specifications published:
- _Change not applicable to Rel-16._
- [TS 26.512 V17.3.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-h30.zip).
