### ISSUE TITLE
DASH Media Player – APIs and Functions - M8 interface between application and provider

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/Standards#29]
# Problem description
26.512 Section 13.2.1 Figure 13.2.1-1 provides an overview of the interfaces between media player and application. In addition, the M8d interface is defined as a connection between `5GMSd-Aware Application` and `Application Server`. Shouldn't this be the `5GMSd Application Provider` instead of the `Application Server`?

<img width="950" alt="Bildschirmfoto 2022-10-20 um 17 31 50" src="https://user-images.githubusercontent.com/2427039/196992905-4ee4f77b-0a67-4af4-8cd6-16276e16b4bf.png">

# Suggested solution
Probably replace `Application Server` with `5GMSd Application Provider`

**Comment by rjb1000** [comment]
Note that this issue affects the current Rel-16 specification as well as Rel-17, so two Change Requests are needed.

**Comment by rjb1000** [comment]
# Proposed replacement figure 13.2.1-1
<img width="100%" alt="3GPP 5GMS Client architecture - Figure 13 2 1-1 (DASH Client) 2022-10-24" src="https://user-images.githubusercontent.com/9865771/197587062-e91e7fe4-d7ea-45c1-bd6e-df453f469a48.png">

**Comment by rjb1000** [comment]
Latest draft CRs available to 5G-MAG members on Causeway as [CDT0107.3GPP SA4#121 TS26.512 API corrections](https://member.5g-mag.com/wg/CD-T/document/910).

**Comment by rjb1000** [comment]
Formal CRs submitted to SA4#121:
- Rel-16 CR0027 in [S4-221250](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_121_Toulouse/Docs/S4-221250.zip).
- Rel-17 CR0028 in [S4-221251](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_121_Toulouse/Docs/S4-221251.zip).

**Comment by rjb1000** [comment]
The following Change Requests were agreed at SA4#121 Closing Plenary yesterday afternoon:

- TS 26.512:
  - Rel-16: CR0027r2 S4-221605.
  - Rel-17: CR0028r2 S4-221606.

**Comment by rjb1000** [comment]
Change Requests approved at SA#98-e:
- Rel-16: **CR0027r2** in [SP-221042](https://portal.3gpp.org/ngppapp/CreateTdoc.aspx?mode=view&contributionId=1394078).
- Rel-17: **CR0028r2** in [SP-221043](https://portal.3gpp.org/ngppapp/CreateTdoc.aspx?mode=view&contributionId=1394079).

**Comment by rjb1000** [comment]
New specifications published:
- [TS 26.512 V16.8.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-g80.zip).
- [TS 26.512 V17.3.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-h30.zip).
