### ISSUE TITLE
Documentation inconsistencies for conflict response when destroying resources referenced by the current Content Hosting Configuration

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/Standards#32]
# Context

During development of the M3 API prototype under https://github.com/5G-MAG/rt-common-shared/pull/14#issuecomment-1326181856, some improvements to error handling in the M1 provisioning APIs have been identified.

# Description
There are resources which can be created by an Application Provider, associated with a Provisioning Session, by using the M1 interface to the 5GMS Application Function, which are later referenced by a Content Hosting Configuration.

- TS 26.512[^1] clause 4.3.5.5 states that a _409 Conflict_ shall be returned if an attempt is made to destroy a **Content Preparation Template** resource which is currently referenced by an active Content Hosting Configuration.
  - But neither table 7.4.2-1 nor clause 7.4.4 indicates that a _409 Conflict_ may be returned in this scenario.
  - Furthermore, the OpenAPI YAML for ServerCertificateProvisioning in clause C.3.2 does not list `200`, `404` or `409` as responses to a `delete` operation even though these are described in clause 4.3.5.5.
- TS 26.512[^1] clause 4.3.6.7 states that a _409 Conflict_ shall be returned if an attempt is made to destroy a **Server Certificate** resource which is currently referenced by an active Content Hosting Configuration.
  - But neither table 7.3.2-1 nor clause 7.3.4 indicates that a _409 Conflict_ may be returned is this scenario.
  - Furthermore, the OpenAPI YAML for ContentPreparationTemplatesProvisioning in annex C.3.3 does not  list `200` or `409` as responses to a `delete` operation even though these are described in clause 4.3.6.7.

[^1]: TS 26.512 v17.2.0

# Suggested solution
1. Add some text to table 7.3.2-1 and/or clause 7.3.4 indicating that an attempt to destroy a Server Certificate that is referenced in the current Content Hosting Configuration will result in a _409 Conflict_.
1. Add some text to table 7.4.2-1 and/or clause 7.4.4 indicating that an attempt to destroy a Content Preparation Template that is referenced in the current Content Hosting Configuration will result in a _409 Conflict_.
1. Add responses for 200, 404 and 409 to the OpenAPI YAML for the `/provisioning-sessions/{provisioningSessionId}/certificates/{certificateId}` path `delete` operation in clause C.3.2.
1. Add responses for 200 and 409 to OpenAPI YAML for the `/provisioning-sessions/{provisioningSessionId}/content-preparation-templates/{contentPreparationTemplateId}` path `delete` operation in clause C.3.3.

**Comment by rjb1000** [comment]
>     1. Add some text to table 7.3.2-1 and/or clause 7.3.4 indicating that an attempt to destroy a Server Certificate that is referenced in the current Content Hosting Configuration will result in a _409 Conflict_.
> 
>     2. Add some text to table 7.4.2-1 and/or clause 7.4.4 indicating that an attempt to destroy a Content Preparation Template that is referenced in the current Content Hosting Configuration will result in a _409 Conflict_.

We haven't specified error conditions in any of the other API resource structures in clause 7.x.2, nor in the 
operations under 7.x.4. My preference is to stick with the pretty unambiguous definition of _409 (Conflict)_ under clauses 4.3.5.5 and 4.3.6.7.

>     3. Add responses for 200, 404 and 409 to the OpenAPI YAML for the `/provisioning-sessions/{provisioningSessionId}/certificates/{certificateId}` path `delete` operation in clause C.3.2.
> 
>     4. Add responses for 200 and 409 to OpenAPI YAML for the `/provisioning-sessions/{provisioningSessionId}/content-preparation-templates/{contentPreparationTemplateId}` path `delete` operation in clause C.3.3.

Propose to follow these last two proposals only.

**Comment by rjb1000** [comment]
Contributions to 3GPP **SA4#122** addressing this issue:
* TS 26.512:
  * Rel-16: **CR0031** in [S4-230041](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_122_Athens/Docs/S4-230041.zip).
  * Rel-17: **CR0032** in [S4-230042](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_122_Athens/Docs/S4-230042.zip).

**Comment by rjb1000** [comment]
Contributions revised and approved at 3GPP **SA4#122** Closing Plenary:
* TS 26.512:
  * Rel-16: **CR0031r1** in [S4-230266](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_122_Athens/Docs/S4-230266.zip).
  * Rel-17: **CR0032r2** in [S4-230267](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_122_Athens/Docs/S4-230267.zip).

**Comment by rjb1000** [comment]
New specifications published by 3GPP MCC:
* TS 26.512:
  * [V16.9.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-g90.zip).
  * [V17.4.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-h40.zip).

(Transcription into equivalent ETSI Technical Specifications to follow in due course.)
