### ISSUE TITLE
Add signalling for asynchronous destruction of Provisioning Session at reference point M1

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/Standards#34]
# Description
The operation to destroy a Provisioning Session, specified in TS 26.512 clause 4.3.2.5, requires that all subresources of that Provisioning Session (server certificates, Content Hosting Configurations, etc.) are also destroyed.

This operation may involve destroying resources that have been configured on 5GMS Application Servers.

This leaves the 5GMS Application Function with two choices:
1. (Synchronous) Wait while resources configured on 5GMS Application Servers are destroyed before confirming the destruction to the M1 client.
    - This could take a while, due to communication with one or more 5GMS Application Servers, risking the M1 client timing out the request.
1. (Asynchronous) Tell the M1 client that the `ProvisioningSession` and all its subresources have been destroyed and get on with the destruction in the background.
    - This gives the M1 client the impression the Provisioning Session resource is gone when it will still be active for a short time. 

It would be advantageous for the 5GMS Application Function to be able to advise the M1 client which mode of operation, synchronous or asynchronous, it has chosen to do. The introduction of a `202 Accepted` response when the 5GMS Application Function is going to perform the operation asynchronously would allow the M1 client to know that the Provisioning Session and all its resources are pending destruction and will be removed shortly. The existing `204 No Content` response can then be used for when the 5GMS Application Function performs the destruction operation synchronously.

# Suggested solution
Introduce a `202 Accepted` response in TS 26.512 clauses 4.3.2.5 and C.3.1, used by the 5GMS AF to indicate that the destruction of the Provisioning Session will be performed asynchronously. After this response is returned, it will no longer be valid for an M1 client to retrieve the Provisioning Session resource, and `404 Not Found` will be returned in response to the retrieval operation.

The `204 No Content` response will only be returned by the 5GMS AF when the destruction operation has (successfully) been performed synchronously.

**Comment by rjb1000** [comment]
Contributions revised and approved at 3GPP **SA4#122** Closing Plenary:
* TS 26.512:
  * Rel-16: **CR0031r1** in [S4-230266](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_122_Athens/Docs/S4-230266.zip).
  * Rel-17: **CR0032r2** in [S4-230267](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_122_Athens/Docs/S4-230267.zip).

**Comment by rjb1000** [comment]
New specifications published by 3GPP MCC:
* TS 26.512:
  * [V16.9.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-g90.zip).
  * [V17.4.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-h40.zip).

(Transcription into equivalent ETSI Technical Specifications to follow in due course.)
