### ISSUE TITLE
Use of url format for ContentHostingConfiguration.entryPointPath at M1 can disallow relative paths

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/Standards#36]
# Description
In TS 26.512 v17.3.0 Annex C.3.5 the OpenAPI YAML uses the `TS26512_CommonData.yaml#/components/schemas/Url` type for the `ContentHostingConfiguration.entryPointPath` which is a `type: string` with `format: uri`.

OpenAPI 3.0 uses the JSON Schema to specify the `type` and `format` combinations available. For the `string` type the `uri` format is specified as being the URI from RFC 3986. However this statement is ambiguous as it does not specify whether it is referring to URI as the thing specified by RFC 3986 or to the `URI` BNF element specified within RFC 3986. Some JSON Schema parsers and OpenAPI processors have chosen the latter, limiting the strings to URIs which follow `scheme ":" hier-part [ "?" query ] [ "#" fragment ]`. Since this format mandates the scheme, a simple relative path is not permitted.

My understanding is that the `ContentHostingConfiguration.entryPointPath` property is supposed to hold a relative path, but cannot if the `uri` format is used in the strict sense by an OpenAPI processor (such an example tool is the [openapi-generator](https://github.com/OpenAPITools/openapi-generator)).

The JSON Schema (Draft 6 and above) also contains a `uri-reference` format which explicitly uses the `URI-Reference` BNF node from RFC 3986. This format represents either a full URI or a relative path.

# Suggested solution
Change the `entryPointPath` data type from:
```yaml
entryPointPath:
    $ref: TS26512_CommonData.yaml#/components/schemas/Url
```
to
```yaml
entryPointPath:
    type: string
    format: uri-reference
```
This removes the ambiguity and will allow relative paths in this field in all OpenAPI processors.

**Comment by rjb1000** [comment]
Problem description seems reasonable, @davidjwbbc, but I think a better solution would be to update TS26512_CommonData.yaml as follows:

1. Define a new `RelativeUrl` common data type for relative URLs, based on the newer `uri-reference` JSON Schema type and conforming to `relative-ref` production in RFC 3986. (Both query and fragment suffixes are permitted.)
1. Clarifying that the base URLs are absolute by introducing a new `AbsoluteUrl` common data type (based on the disambiguated `uri` JSON Schema type and conforming to the `absolute-URI` production in RFC 3986. (Query string is permitted but not fragment identifier.)
1. The original `Url` common data type can remain in TS26512_CommonData.yaml, but is redefined to be the JSON Schema type `uri-reference` with a description indicating conformance with the `URI-reference` production in RFC 3986 which encompasses either a `URI` or a `relative-URI` (for reasons of backwards compatibility).

TS26512_M1_ContentHostingProvisioning.yaml is updated to use the new common data types.

Prototypes here:
- [TS26512_CommonData.yaml.txt](https://github.com/5G-MAG/Standards/files/10236796/TS26512_CommonData.yaml)
- [TS26512_M1_ContentHostingProvisioning.yaml.txt](https://github.com/5G-MAG/Standards/files/10236805/TS26512_M1_ContentHostingProvisioning.yaml)

**Comment by davidjwbbc** [comment]
The TS26512_CommonData.yaml linked above is missing the last part of the file, I've replaced it in the version I've used by grabbing the extra `component/schemas`  from the v17.2.0 version.

**Comment by rjb1000** [comment]
Contributions to 3GPP **SA4#122** addressing this issue:
* TS 26.512:
  * Rel-16: **CR0031** in [S4-230041](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_122_Athens/Docs/S4-230041.zip).
  * Rel-17: **CR0032** in [S4-230042](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_122_Athens/Docs/S4-230042.zip).

**Comment by rjb1000** [comment]
Contributions revised and approved at 3GPP **SA4#122** Closing Plenary:
* TS 26.512:
  * Rel-16: **CR0031r1** in [S4-230266](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_122_Athens/Docs/S4-230266.zip).
  * Rel-17: **CR0032r1** in [S4-230267](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_122_Athens/Docs/S4-230267.zip).

**Comment by rjb1000** [comment]
CR pack [SP-250253](https://portal.3gpp.org/ngppapp/CreateTdoc.aspx?mode=view&contributionUid=SP-230253) approved at SA#99 Plenary meeting in Rotterdam.

**Comment by rjb1000** [comment]
New specifications published by 3GPP MCC:
* TS 26.512:
  * [V16.9.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-g90.zip).
  * [V17.4.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-h40.zip).

(Transcription into equivalent ETSI Technical Specifications to follow in due course.)
