### ISSUE TITLE
Section 5.2.2.1: Deployment with separated Core and RAN functions

### ISSUE THREAD

**Issue by johannmika** [5G-MAG/Standards#4]
**Description of the problem**
Section 5.2.2.1: "Deployment with separated Core and RAN functions" (p.18) limits the integration of the core functions to a single physical device:
`In a typical deployment of an LTE-based 5G Broadcast System, the core functions of the MBMS GW, MME and
BM-SC may be integrated into a single physical device that manages all the 5G Broadcast Services of a 5G Broadcast
System`

**Suggested solution**
- Extend the section or add a new one including also virtualized systems and possible (geo-)redundant deployments for a system with core functions with common (logical single) interfaces M1, M3, xMB, Uu.
- Add (informative) suggestions/best practise examples of operational concepts for network operators

**Additional context**
In a operational environment the typical deployment will most probably not be done on a single physical machine. Mechanisms to ensure reliability and failsafe operation might include other advanced concepts.

**Comment by rjb1000** [comment]
I think that (informative) clause 5.2.2 is intended to be a non-exhaustive list of deployment architectures of the logical reference architecture in clause 5.2.1.

Other deployments of the reference architecture along the lines you mention are perfectly valid, but I don't think they necessarily need to be enumerated in clause 5.2.2, though.

The simplest remedy (other than "do nothing") is to insert a short clause 5.2.2.0 ("General") explaining that the deployments listed are just two of many possibilities.

**Comment by jordijoangimenez** [comment]
Refer to: [CR_ETSI103720_Issue4.docx](https://member.5g-mag.com/wg/CD-T/document/708)

**Comment by jordijoangimenez** [comment]
RESOLVED - it can still be reviewed
