### ISSUE TITLE
Reference to MCS indexes / Modulation Order

### ISSUE THREAD

**Issue by jordijoangimenez** [5G-MAG/Standards#47]
# Problem description
The current version of the document does not contain information about the MCS indexes, modulation order, etc applicable.

# Suggested solution description
Add a reference and a table with values from the relevant 3GPP specifications.

**Comment by dvargasparedero** [comment]
I think the procedures to calculate the modulation order (Q_m) and transport block size (TBS) based on the modulation and coding scheme (MCS) are well explained in section 11 of TS 36.213. I would suggest going for your option A). 

Proposed sentence: “Details on the determination of the modulation order (Q_m) and transport block size (TBS) for the PMCH can be found in section 11 of TS 36.213.”

**Comment by jordijoangimenez** [comment]
Addressed here: https://member.5g-mag.com/wg/CD-T/document/974

David, we may still want to generate a second publication (2-pager) extracting the values as the info is quite hidden into hundreds of pages. TBD

**Comment by jordijoangimenez** [comment]
Agreement to work on implementations guidelines with recommended values extracted from https://www.ibc.org/technical-papers/performance-of-5g-broadcast-and-benefits-of-proposed-time-interleaving-enhancements/6745.article

@dvargasparedero and @jordijoangimenez to work on a first version.

**Comment by haudiobe** [comment]
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/2828689/217811175-088d5e84-a419-4297-8e1a-debfb8566680.png)

**Comment by jordijoangimenez** [comment]
Available in https://member.5g-mag.com/wg/CD-T/document/779
