### ISSUE TITLE
TMGIs for Receive Only Mode: ETSI TS 124 116 V15.0.0 and ETSI TS 103 720 do not match?

### ISSUE THREAD

**Issue by johannmika** [5G-MAG/Standards#5]
**Describe the bug**
ETSI TS 124 116 V15.0.0 clause 6.3.2 (p.8) only allows PLMN ID 901 56.
`TMGI assigned to a service for Receive only mode shall have the values of MCC = 901 and MNC = 56.`

ETSI TS 103 720 clause 5.11.2 (p. 29) also allows other PMNC IDs: 
`2) The service provider may use a TMGI with PLMN ID other than 901 56 to provide a 5G Broadcast Service. In
this case, it is the service provider's responsibility to assign a correct MBMS Service ID.`

**Suggested solution**
Update ETSI TS 124 116 clause 6.3.2 to match ETSI TS 103 720 clause 5.11.3.

Note: as this issue is linked to two different standards, I linked it to two projects.

**Comment by rjb1000** [comment]
Hmm... Interesting inconsistency.

Does TS 103 720 supersede TS 124 116 in case of disagreement?

**Comment by haudiobe** [comment]
I believe we are clear that 5G Broadcast services as defined in TS 103 720 are ROM and hence the sentence above 1) is wrong. However, what we could say

`2) A service provider may use a TMGI with PLMN ID other than 901 56 to provide an MBMS User Service that is other conforming to this specification. In this case, it is the service provider's responsibility to assign a correct MBMS Service ID.`

But maybe it is better to remove this overall.

**Comment by jordijoangimenez** [comment]
@jordijoangimenez to review the CR. Gather informative text to explain the two cases.

**Comment by jordijoangimenez** [comment]
Revision of [CR_ETSI103720_Issue5.docx](https://member.5g-mag.com/wg/CD-T/document/709) has been uploaded.
It should now clarify the initial confusion. Result is that any PLMN (not only those with PLMN ID 901 56) can provide 5G Broadcast Services. When those services are ROM the MBMS Service ID starts with 0x0.

![image](https://user-images.githubusercontent.com/87380947/168067972-ad3551f8-9f04-4d6e-a9be-58a6f926f873.png)

**Comment by jordijoangimenez** [comment]
RESOLVED - it can still be reviewed
