### ISSUE TITLE
Change requirement for support of 6/7/8 MHz support

### ISSUE THREAD

**Issue by haudiobe** [5G-MAG/Standards#51]
# Problem description
It is typically the case mobile devices may be configured for a specific market. Hence, it is preferred to not mandate all UHF bandwidth, but only one of those.

# Suggested solution
In clause 7.3.2 of TS 103 720 v1.1.17

Replace:
The UE capabilities indicating the support of 6/7/8 MHz PMCH bandwidths as specified in ETSI TS 136 306 [26] and ETSI TS 136 331 [21] shall be supported.

with:
The UE capabilities indicating support for at least one of the three 6, 7, or 8 MHz PMCH bandwidths as specified in ETSI TS 136 306 [26] and ETSI TS 136 331 [21] shall be supported. The UE should support all three  6, 7, and 8 MHz PMCH bandwidths.

**Comment by jordijoangimenez** [comment]
Available in https://member.5g-mag.com/wg/CD-T/document/779
