### ISSUE TITLE
TMGI/MBMS Service ID allocation (clause 5.11.3 TMGI Management for 5G Broadcast Services)

### ISSUE THREAD

**Issue by johannmika** [5G-MAG/Standards#6]
**Problem description**
Clause 5.11.3:
`MBMS Service IDs are not globally unique in the sense that two service providers may use the same TMGI from the reserved range for different 5G Broadcast Services.`

**Suggested solution**
Identify a solution to use globally unique MBMS service IDs for "Receive Only Mode" network operators and update the standard according to that solution.

**Context**
If user receive content from multiple network operators (e.g. via HPHT in Receive Only Mode) which might be the case in border areas the user will experience services with same TMGIs (PLMN ID 901 56 with same MBMS Service IDs).

**Comment by rjb1000** [comment]
Assigning TMGI values from a unique PLMN ID (MCC+MNC) is the obvious solution that completely avoids the risk of duplicate MBMS Service ID assignments across national borders. This is option 2 in clause 5.11.2. A country-unique MNC assignment can be obtained from your friendly national communications regulator. National assignment policies vary, but you typically just have to be registered with the regulator as a telecommunications service provider to get one.

Clause 5.11.3 emphasises that the 5G Broadcast Receiver needs to be pre-configured to discover services on networks with particular PLMN IDs. Note that this does not require a SIM card in the receiver: it could just be a list of well-known PLMN IDs stored in non-volatile RAM, for example.

Equally, I can't see that there's anything to stop a 5G Broadcast Receiver just scanning the whole LTE radio band to discover MBMS services on all radiated PLMNs. (Somewhat analogous to a DVB-T(2) UHF channel scan.) All the valid numerologies are well specified and fixed for a given 3GPP release. It might take a little while to scan the whole band, but it's a zero-configuration solution.

The second solution (option 1 in clause 5.11.2) is to use the ITU-reserved PLMN ID 901 56 but to co-ordinate MBMS Service ID values on a regional (i.e. cross-border multinational) basis, as recommended by the final paragraph in clause 5.11.3. This solution avoids the need to obtain a country-specific MNC assignment and configure this into the 5G Broadcast Receiver, but requires the limited number space of the MBMS Service ID (20 bits = 1,048,576 unique values, less the 16 values reserved for Broadcast Service Announcements) to be carved up by agreement between adjacent network providers.

Reserving (say) 6 of those bits to encode a broadcast network operator ID would allow for two unique assignments to every EU member state (and then some). That would still leave 14 bits = 16,384 unique MBMS Service IDs (less the 16 values reserved for Broadcast SA) for each network operator to use.

**Comment by jordijoangimenez** [comment]
This issue is to be resolved outside of the ETSI spec.
