### ISSUE TITLE
Clarification on TS 26.512 `ServiceAccessInformation.networkAssistanceConfiguration.serverAddresses` values

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/Standards#60]
# Problem description
3GPP TS 26.512 (v17.4.0) Table 11.2.3.1-1 states that the `networkAssistanceConfiguration.serverAddresses` field contains:
> A list of 5GMS AF addresses (URLs) that offer the APIs for 5GMS AF-based Network Assistance, for access by the 5GMSd Media Session Handler.

However it is unclear how much of the AF URL is needed in this field. As I see it:
1. The minimal would be the `{apiRoot}` from the OpenAPI YAML descriptions, this can then be used by the Media Session Handler to construct the full NetworkAssistance URL for the API version it understands and prefers.
1. The URL could also be `{apiRoot}/3gpp-m5/{apiVersion}/` to indicate the interface at reference point M5 and protocol version to use with that AF, allowing the Media Session Handler to pick one that it understands the protocol version for.
1. Alternatively the URL could be the full URL prefix down to the Network Assistance resource, e.g. `{apiRoot}/3gpp-m5/v2/network-assistance/`, allowing the Media Session Handler to directly use the URL provided in communications as per TS 26.512 Clause 11.6.2. 

# Suggested solution
Specify with example the expected URL structure in Table 11.2.3.1-1 including which path elements the URL shall contain.

My preference would be for option 2 above as this gives prior notification to the Media Session Handler about the API version accepted by the AF for that particular URL.

**Comment by rjb1000** [comment]
This is an example of a wider class of issue, and we could do with clarifying the general case (for consistency). The NOTE to table 11.2.3.1-1 looks like a good place to make this clarification.

There are several server URL address list properties in the Service Access Information:
* `clientConsumptionReportingConfiguration.serverAddresses`.
* `dynamicPolicyInvocationConfiguration.serverAddresses`.
* `clientMetricsReportingConfigurations.serverAddresses`
* `networkAssistanceConfiguration.serverAddresses`.

**Comment by gheikkila** [comment]
I've always thought that the addresses would be complete URLs, i.e. alternative 3. Otherwise we would need to have text describing how to construct the URL, or...?

**Comment by gheikkila** [comment]
Shouldn't answer without first re-reading the spec. In clause 11.4.2 it's clear that the serverAddresses only contain the apiRoot:

![image](https://user-images.githubusercontent.com/7382690/234263654-e7a6f840-b6da-4104-bc0f-c931bb450123.png)

**Comment by rjb1000** [comment]
Good spot, @gheikkila.

So, in addition to clarifying the NOTE to table 11.2.3.1-1, I suppose we need to add equivalent statements to the sentence from clause 11.4.2 you have highlighted in red to the following clauses:
* Consumption reporting: clause 11.3.2.
* Dynamic policies: clause 11.5.2.
* Network assistance: clause 11.6.2.

**Comment by gheikkila** [comment]
I double-checked again, since I became a bit suspicious due to only using my offline version of 26.512. The text I quoted is **NOT** in 26.512! I remember now that we had some discussion (with Charles and others), and that I proposed that we should improve the text in 26.512 to what I pasted. When enabling tracked changes on my local copy I see the following. But this has never been implemented.

![image](https://user-images.githubusercontent.com/7382690/234318974-91a9199c-72bc-4a82-977e-aa97dd7cd372.png)

**Comment by rjb1000** [comment]
Ah. OK. Well, it sounds like this has cropped up before and the text proposal looks like it does the trick.

We should add clause 11.4.2 to the list of proposed fixes as well, in that case.

**Comment by gheikkila** [comment]
Check the discussion in https://github.com/5G-MAG/Standards/issues/46

**Comment by rjb1000** [comment]
> Check the discussion in #46

Aha! Thanks for the detective work, @gheikkila. It looks like the extended scope recorded in the comments wasn't included in the CR agreed in Athens. Hence, the fix does not appear in TS 26.512 V17.4.0. Let's try and fix it properly now.

**Comment by rjb1000** [comment]
Regarding @davidjwbbc's three options above, he makes a good argument for including the path _up to and including `apiVersion`_, i.e., his option 2. Without this additional information, the Media Session Handler has to guess the API version number.

I will draft a contribution along these lines therefore.

**Comment by rjb1000** [comment]
The generic formulation is thus:
> _{apiRoot}_/3gpp-m5/_{apiVersion}_/XXXX
> where the first three elements shall be substituted by the 5GMS Client with one of the URLs selected from the `XXXXConfiguration.serverAddresses` array of the `ServiceAccessInformation` resource (see clause 11.2.3.1).

**Comment by rjb1000** [comment]
One potential advantage of this design is that a 5GMS AF that implements both (say) Rel-16 and Rel-17 endpoints at reference point M5 could advertise them as different server addresses, one with _{apiVersion}_ = "v1" and the other with _{apiVersion}_ = "v2". An implementation of the Media Session Handler that understands the M5 API versioning scheme would then be able to discard any endpoints that it is not compatible with.

Having said that, maybe it would be better for the Media Session Handler to advertise its level of specification compliance in the `User-Agent` request header of its Service Access Information request. Then the 5GMS AF could include only compatible server addresses in the Service Access Information resource it returns.

**Comment by rjb1000** [comment]
CR drafted for review at post-SA4#123 _ad hoc_ meeting on 11th May:
* TS 26.512 CR0033r3 "[5GMS3] Rel-17 corrections" in [S4aI230092](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/3GPP_SA4_AHOC_MTGs/SA4_MBS/Docs/S4aI230092.zip).

**Comment by rjb1000** [comment]
Revised CR contributed to SA4#124 (Berlin):
* TS 26.512 CR0033r3 "[5GMS3] Rel-17 corrections" in [S4-230771](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_124_Berlin/Docs/S4-230771.zip).

**Comment by rjb1000** [comment]
CRs agreed during SA4#124 (Berlin):
* TS 26.512 CR0033r5 "[5GMS3, TEI17] Rel-17 corrections" in [S4-230968](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_124_Berlin/Docs/S4-230968.zip)
* TS 26.512 CR0035 "[5GMS3] Rel-16 corrections" in [S4-230976](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_124_Berlin/Docs/S4-230976.zip)

**Comment by rjb1000** [comment]
CR Pack [SP-230546](https://www.3gpp.org/ftp/TSG_SA/TSG_SA/TSGS_100_Taipei_2023-06/Docs/SP-230546.zip) including TS 26.512 CR0033r5 (Rel-17) and CR0035 (Rel-16) **approved** at SA#100 (Taipei).

**Comment by rjb1000** [comment]
:mega: 3GPP TS 26.512 **V16.10.0** and **V17.5.0** are now published:
- https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-ga0.zip
- https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-h50.zip
