### ISSUE TITLE
MBMS broadcast service provision: clarification of "MBMS notification" and "MBMS scheduling information"

### ISSUE THREAD

**Issue by johannmika** [5G-MAG/Standards#7]
**Problem description**
- In my understanding, "MBMS notification" is a bit confusing as it seems to be the same as "MBMS Scheduling Information".
- In my understanding, M2AP (ETSI TS 136 443) protocol is used for MBMS broadcast service provision but is not linked within the document. 

**Suggested solution**
Link to M2AP (ETSI TS 136 443) clause 8.x.y for MBMS broadcast service provision (Session start/stop, MBMS Scheduling Information)

**Comment by dvargasparedero** [comment]
MBMS scheduling information is present in reference point M2 which is not exposed in TS 103 720.
