### ISSUE TITLE
Possible inconsistency in specification of Service Data Flow Description

### ISSUE THREAD

**Issue by rjb1000** [5G-MAG/Standards#74]
# Context

Clause 11.5.4 of TS 26.512 states:

> The Dynamic Policy resource contains a `serviceDataFlowDescription` property which contains the service data flow template according to TS 23.503. The `ServiceDataFlowDescription` **shall contain one of**:
> - a `flowDescription` object (including 5-Tuples, Type of Service, Security Parameter Index, etc.).
> - a `domainName`.

This implies that `flowDescription` and `domainName` are mutually exclusive properties.

(A `ServiceDataFlowDescription` is also supplied by the Media Session Handler when creating a new Network Assistance session, per clause 11.6.3.1.)

Clause 6.4.3.2 specified the `ServiceDataFlowDescription` data type as having the above two properties, which are both specified as being optional. The following sentence appears at the end of this clause:

> An object of type `ServiceDataFlowDescription` **shall contain at least one property**.

# Problem description

The two normative statements highlighted above appear to be contradictory.

# Suggested solution

1. Adjust the text at clause 6.4.3.2 to state that *exactly one* of the properties shall be present in `ServiceDataFlowDescription`.
2. Add some text to clause 11.6.4 (Network Assistance API) to match the text at clause 11.5.4 (Dynamic Policies API).
3. Adjust the OpenAPI at clause C.2 to specify that `flowDescription` and `domainName` are mutually exclusive using the `oneOf` YAML keyword.
   - https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

**Comment by rjb1000** [comment]
@tlohmar: please confirm that the suggested remedy was your original intent when specifying the Dynamic Policy instantiation API.

**Comment by tlohmar** [comment]
> This implies that flowDescription and domainName are mutually exclusive properties.

hmm, I consistently read `onle of`. How do you conclude, that the two properties are mutually exclusive on M5?

**Comment by rjb1000** [comment]
Ah... I see where you are coming from now, @tlohmar. You are saying that the data type is loosely defined on purpose at clause 6.4.3.2 to allow for future flexibility, but the additional constraint for Dynamic Policies is additionally specified on top of that in clause 11.5.4. And this explains why the constraint is not enforced by the OpenAPI specification of the `ServiceDataFlowDescription` data type.

This is rather unfortunate, in my opinion. It would be quite nice to enforce this in the OpenAPI syntax if possible. Otherwise, the implementer has to join the dots to enforce the constraint in custom code for each usage of the data type where the constraint applies.

The only other usage of the `ServiceDataFlowDescription` data type at the moment in TS 26.512 is for creating a new Network Assistance session (clause 11.6.3.1). The "eaxactly one of" constraint is _not_ explicitly stated here, but I suspect it applies in just the same way at for instantiating a Dynamic Policy.

If we ever have a need to describe service data flows with _both_ an IP Packet Filter Set _and_ a domain name, I would suggest we define a different data type with different constraints. That makes things nice and explicit in the OpenAPI with no ambiguity. And these constraints can be enforced by the code automatically generated by compiling the OpenAPI YAML.

Hence, unless there is a good reason not to, I would advocate amending clause 6.4.3.2 and the OpenAPI syntax to make the "exactly one of" constraint explicit.

**Comment by rjb1000** [comment]
Any additional thoughts, @ibouazizi?

**Comment by tlohmar** [comment]
> This is rather unfortunate, in my opinion. It would be quite nice to enforce this in the OpenAPI syntax if possible. 
Yes, I agree. Would be better to have more in the OpenAPI syntax. My earlier comment was more on the reason for change `The two normative statements highlighted above are contradictory.`

**Comment by rjb1000** [comment]
Initial prototyping suggests that it's difficult to enforce `oneOf` in the OpenAPI YAML syntax without resorting to polymorphic data types. It works, but it is difficult to document.

I might just make the simple clarification in clause 6.4.3.2, so that at least the cardinality of the members is clearly specified in a common location.

**Comment by rjb1000** [comment]
Proposed clarification in clause 6.4.3.2 endorsed at post-SA4#124 _ad hoc_ meeting:
- TS 26.512 **CR0037** Rel-17 "[5GMS3, TEI17] Essential maintenance" in [S4aI230105](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/3GPP_SA4_AHOC_MTGs/SA4_MBS/Docs/S4aI230105.zip).

**Comment by rjb1000** [comment]
CR contributed to SA4#125 by @rjb1000:

* TS 26.512
  * Rel-16: **CR0043** "Essential maintenance" in [S4-231158](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_125_Gotheneburg/Docs/S4-231158.zip).
  * Rel-17: **CR0037** "Essential maintenance" in [S4-231156](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_125_Gotheneburg/Docs/S4-231156.zip).

**Comment by rjb1000** [comment]
CRs agreed at SA4#125:

* TS 26.512
  * Rel-16: **CR0043**r1 "Essential maintenance" in [S4-231425](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_125_Gotheneburg/Docs/S4-231425.zip).
  * Rel-17: **CR0037**r2 "Essential maintenance" in [S4-231424](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_125_Gotheneburg/Docs/S4-231424.zip).

**Comment by rjb1000** [comment]
CRs revised (YAML corrections) and approved at SA#101:

* TS 26.512
  * Rel-16: **CR0043**r2 "Essential maintenance" in [SP-231082](https://www.3gpp.org/ftp/TSG_SA/TSG_SA/TSGs_101_Bangalore_2023-09/Docs/SP-231082.zip).
  * Rel-17: **CR0037**r3 "Essential maintenance" in [SP-231053](https://www.3gpp.org/ftp/TSG_SA/TSG_SA/TSGs_101_Bangalore_2023-09/Docs/SP-231053.zip).
