### ISSUE TITLE
NetworkAssistanceSession request body not specified in the OpenAPI YAML for M5 createNetworkAssistanceSession operation

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/Standards#76]
# Context

_This issue refers to TS 26.512 V17.5.0._

Clause 4.7.6 describes the procedure for creating a Network Assistance session:

> The 5GMS Client first creates a Network Assistance Session with its chosen 5GMS AF instance. **It provides information that will be used by the Network Assistance function to request QoS from the PCF and to recommend a bit rate to the 5GMS Client.**

Table 11.6.2-1 describes the "Create Network Assistance Session resource" operation and in table 11.6.3.1-1 it is indicated, in the Cardinality and Usage columns, that the `serviceDataFlowInformation`, `policyTemplateId` and `requestedQoS` are optional fields that can be provided during the create operation ("C: RW").

# Problem description

- Clause 11.6.4 does not specify that the create operation provides a `NetworkAssistanceSession` resource in the creation request body, this is only implied by the Usage column in table 11.6.3.1-1.
- The YAML in Clause C.4.5 does not specify that the `createNetworkAssistanceSession` operation takes a request body.

So according to the YAML there is no body in the create request, but table 11.6.3.1-1 indicates that some `NetworkAssistanceSession` resource fields can be written during resource creation.

# Suggested solution
Improve Clause 11.6.4 by stating that the `POST` method to create a Network Assistance Session resource shall contain a `NetworkAssistanceSession` resource object in the request body. e.g. change the first paragraph to:
> The 5GMS Client uses the POST method to create a Network Assistance session with the 5GMS AF. The 5GMS client may provide an initial set of parameters for the Network Assistance Session by providing a `NetworkAssistanceSession` resource in the request body. The AF returns the Network Assistance session identifier if session setup was successful, otherwise an error code is returned without a Network Assistance session identifier.

Add the specification for a request body to the OpenAPI YAML in clause C.4.5:
```yaml
...
paths:
  /network-assistance/:
    post:
      operationId: createNetworkAssistanceSession
      summary: 'Create a new Network Assistance Session.'
      requestBody:
        description: 'The initial parameters for the Network Assistance Session resource'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetworkAssistanceSession'
      responses:
        '201':
          description: 'Created Network Assistance Session'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkAssistanceSession'
          headers:
            Location:
              description: 'The URL of the nely created Network Assistance Session resource'
              required: true
              schema:
                $ref: 'TS26512_CommonData.yaml#/components/schemas/AbsoluteUrl'
        '400':
          description: 'Bad Request'
        '401':
          description: 'Unauthorized'
...
```

**Comment by rjb1000** [comment]
Agree this is a discrepancy in the specification of the Network Assistance Session that needs fixing, @davidjwbbc.

I suspect that the solution evolved over time and the specification didn't keep up with that.

**Comment by rjb1000** [comment]
I will propose a fix in CR0037.

**Comment by rjb1000** [comment]
CRs agreed at SA4#125:

* TS 26.512
  * Rel-16: **CR0043**r1 "Essential maintenance" in [S4-231425](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_125_Gotheneburg/Docs/S4-231425.zip).
  * Rel-17: **CR0037**r2 "Essential maintenance" in [S4-231424](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_125_Gotheneburg/Docs/S4-231424.zip).

**Comment by rjb1000** [comment]
CRs revised (YAML corrections) and approved at SA#101:

* TS 26.512
  * Rel-16: **CR0043**r2 "Essential maintenance" in [SP-231082](https://www.3gpp.org/ftp/TSG_SA/TSG_SA/TSGs_101_Bangalore_2023-09/Docs/SP-231082.zip).
  * Rel-17: **CR0037**r3 "Essential maintenance" in [SP-231053](https://www.3gpp.org/ftp/TSG_SA/TSG_SA/TSGs_101_Bangalore_2023-09/Docs/SP-231053.zip).

**Comment by rjb1000** [comment]
Approved changes published and available for download:
* TS 26.512 [V16.11.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-gb0.zip)
* TS 26.512 [V17.6.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-h60.zip)
