### ISSUE TITLE
5GMSd - QoE Metrics Reporting - Inconsistency with HTTPList

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/Standards#79]
# Problem description
- TS 26.512 clause 11.4.3 defines the metrics reporting format to be used for 5G Media Streaming referencing the scheme `urn:3GPP:ns:PSS:DASH:QM10` and TS 26.247 clause 10.6.1 and 10.6.2.
- TS26.247 clause 10.4 lists all the relevant quality metrics for DASH. `HTTPList` is not included in this list but _does_ appear in the schema definition in clause 10.6.2 despite not being referenced from anywhere TS 26.247.

@rjb1000 digged deeper into this and found that `HTTPList` has been removed from TS 26.247 V14.0.0 by CR0093r1 (agreed at SA4#92 as [S4-170227](http://portal.3gpp.org/ngppapp/DownloadTDoc.aspx?contributionUid=S4-170227) and approved at SA#75 as [SP-170027](http://portal.3gpp.org/ngppapp/DownloadTDoc.aspx?contributionUid=SP-170027)).

> **Summary of change:** Remove the HttpList metric from the QoE reporting.
> **Reason for change:** The HttpList metrics report includes the media URL used, which can be seen as sensitive information for the end-user. As the HttpList metric is not necessary for almost any QoE-related use-case, this privacy breach is not motivated.
> **Consequences if not approved:** Privacy breach, or possibly we need to add active end-user consent to (at least parts of) the QoE reporting concept.

More details can be found in the comment here: https://github.com/5G-MAG/rt-5gms-media-stream-handler/issues/35#issuecomment-1630631328 

# Suggested solution
To avoid confusion, `HTTPList` and all the related definitions should be removed from the schema definition in clause 10.6.2.

**Comment by rjb1000** [comment]
As rapporteur of TS 26.247, @haudiobe will look at raising mirror CRs to remove the redundant type definitions from the schema.

- `QoeMetricType`: Remove `<xs:element name="HttpList" type="HttpListType"/>`.
- `HttpListType`: Delete schema type.
- `HttpListEntryType`: Delete schema type.
- `HttpEntryResourceType`: Delete schema type.
- `StringPatternType`: Delete schema type.
- `ExtensibleHttpEntryResourceType`: Delete schema type.
- `HttpThroughputTraceType`: Delete schema type.

There is a question outstanding about how compliance with a particular version of the schema version should be signalled in instance documents (reception reports):
- We could change the **schema name space identifier** (currently `urn:3gpp:metadata:2011:HSD:receptionreport`).
- Alternatively, we could specify that a **schema version number** needs to be explicitly signalled using an attribute in the root element of the document: `ReceptionReport@sv:schemaVersion`.
  - A suitable type for this is already specified in the (diminutive) companion schema `urn:3gpp:metadata:2016:PSS:schemaVersion`, but not used by the main reporting schema, for some reason.

```xml
<xs:complexType name="QoeMetricType">
	<xs:choice>
		<xs:element name="HttpList" type="HttpListType"/>
		<xs:element name="RepSwitchList" type="RepSwitchListType"/>
		<xs:element name="AvgThroughput" type="AvgThroughputType" maxOccurs="unbounded"/>
		<xs:element name="InitialPlayoutDelay" type="xs:unsignedInt"/>
		<xs:element name="BufferLevel" type="BufferLevelType"/>
		<xs:element name="PlayList" type="PlayListType"/>
		<xs:element name="MPDInformation" type="MpdInformationType" maxOccurs="unbounded"/>
		<xs:element name="PlayoutDelayforMediaStartup" type="xs:unsignedInt"/>
	</xs:choice>
	<xs:anyAttribute processContents="skip"/>
</xs:complexType>
<xs:complexType name="HttpListType">
	<xs:choice>
		<xs:element name="HttpListEntry" type="HttpListEntryType" maxOccurs="unbounded"/>
	</xs:choice>
	<xs:anyAttribute processContents="skip"/>
</xs:complexType>
<xs:complexType name="HttpListEntryType">
	<xs:choice>
		<xs:element name="Trace" type="HttpThroughputTraceType" maxOccurs="unbounded"/>
	</xs:choice>
	<xs:attribute name="tcpid" type="xs:unsignedInt" use="optional"/>
	<xs:attribute name="type" type="ExtensibleHttpEntryResourceType" use="optional"/>
	<xs:attribute name="url" type="xs:string" use="required"/>
	<xs:attribute name="actualUrl" type="xs:string" use="optional"/>
	<xs:attribute name="range" type="xs:string" use="optional"/>
	<xs:attribute name="trequest" type="xs:dateTime" use="required"/>
	<xs:attribute name="tresponse" type="xs:dateTime" use="required"/>
	<xs:attribute name="responsecode" type="xs:unsignedInt" use="optional"/>
	<xs:attribute name="interval" type="xs:unsignedInt" use="optional"/>
	<xs:anyAttribute processContents="skip"/>
</xs:complexType>
<xs:simpleType name="HttpEntryResourceType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="MPD"/>
		<xs:enumeration value="MPDDeltaFile"/>
		<xs:enumeration value="XLinkExpansion"/>
		<xs:enumeration value="InitializationSegment"/>
		<xs:enumeration value="IndexSegment"/>
		<xs:enumeration value="MediaSegment"/>
	</xs:restriction>
</xs:simpleType>
<xs:simpleType name="StringPatternType">
	<xs:restriction base="xs:string">
		<xs:pattern value="x:\S.*"/>
	</xs:restriction>
</xs:simpleType>
<xs:simpleType name="ExtensibleHttpEntryResourceType">
	<xs:union memberTypes="HttpEntryResourceType StringPatternType"/>
</xs:simpleType>
<xs:complexType name="HttpThroughputTraceType">
	<xs:attribute name="s" type="xs:dateTime" use="required"/>
	<xs:attribute name="d" type="xs:unsignedInt" use="required"/>
	<xs:attribute name="b" type="UnsignedIntVectorType" use="required"/>
	<xs:anyAttribute processContents="skip"/>
</xs:complexType>
```

**Comment by rjb1000** [comment]
CRs agreed at SA4#125:

* TS 26.247
  * Rel-14: Not contributed.
  * Rel-15: Not contributed.
  * Rel-16: **CR0181**r3 "Removal of HTTPList from 3GPP Metrics" in [S4-231516](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_125_Gotheneburg/Docs/S4-231516.zip).
  * Rel-17: **CR0182**r3 "Removal of HTTPList from 3GPP Metrics" in [S4-231517](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_125_Gotheneburg/Docs/S4-231517.zip).

**Comment by rjb1000** [comment]
CR Pack [SP-230912](https://www.3gpp.org/ftp/TSG_SA/TSG_SA/TSGs_101_Bangalore_2023-09/Docs/SP-230912.zip) approved at SA#101:

* TS 26.247
  * Rel-16: **CR0181**r3 "Removal of HTTPList from 3GPP Metrics".
  * Rel-17: **CR0182**r3 "Removal of HTTPList from 3GPP Metrics".

**Comment by rjb1000** [comment]
Approved changes published and available for download:
* TS 26.247 [V16.8.1](https://www.3gpp.org/ftp/Specs/archive/26_series/26.247/26247-g81.zip)
* TS 26.247 [V17.4.1](https://www.3gpp.org/ftp/Specs/archive/26_series/26.247/26247-h41.zip)
