### ISSUE TITLE
3GPP TS 26.346 - Wrong RFC referenced for "Compact No-Code" FEC

### ISSUE THREAD

**Issue by samhurst** [5G-MAG/Standards#87]
# Context
The following clauses of 3GPP TS 26.346 reference IETF [RFC 5052](https://datatracker.ietf.org/doc/rfc5052/) as containing the specification of the "Compact No-Code" FEC scheme:
- 7.2.2.
- 7.2.3.
- 7.2.7.
- L.4.7.

# Problem description
RFC 5052 contains no references to the Compact No-Code FEC scheme, which is instead specified in [RFC 3695](https://datatracker.ietf.org/doc/html/rfc3695).

(Clause 7.1 correctly references RFC 5052 in the context of the FEC Building Block, so reference [12] should remain in that case.)

# Suggested solution
Replace citations in the affected clauses with RFC 3695 [13], where the Compact No-Code FEC Scheme is specified.

**Comment by rjb1000** [comment]
Note that TS 26.346 still refers to the (obsolete) [RFC 3695](https://datatracker.ietf.org/doc/html/rfc3695) rather than the newer RFC 5445.

**Comment by samhurst** [comment]
This could be incorporated into TS26.346 CR0669 [S4-231700]

**Comment by haudiobe** [comment]
Prepared already - sent to @rjb1000

**Comment by rjb1000** [comment]
CR contributed by @haudiobe was agreed:

* TS 26.346 Rel-17 **CR0669**r1 "FEC-OTI-Maximum-Source-Block-Length for FEC Compact-No-Code" in [S4-231902](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_126_Chicago/Docs/S4-231902.zip).

**Comment by rjb1000** [comment]
CR Pack [SP-231374](http://portal.3gpp.org/ngppapp/DownloadTDoc.aspx?contributionUid=SP-231374) approved at SA#102 (Edinburgh).

**Comment by rjb1000** [comment]
TS 26.346 [V17.4.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.346/26346-h40.zip) published.
