### ISSUE TITLE
TS 26.512 - Use of Read-only mandatory fields in PolicyTemplate resource

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/Standards#88]
## Description
The _PolicyTemplate_ resource specified in TS 26.512 table 7.9.3-1 has several mandatory fields (*Cardinality* is `1..1`) which are also read-only (all *Usage* operations are marked **RO** or **-**), meaning that they are only meaningful in API responses. The OpenAPI YAML specification in clause C.3.8 only marks these properties as being *required* meaning that the property is expected in both requests and responses. In fact, they should only be present in responses. In requests, these properties need to be ignored by the 5GMS AF.

There is therefore a discrepancy between table 7.9.3-1 and Annex C.3.8. 

## Suggested solution
Add the `readOnly: true` flag to the read-only mandatory fields in the OpenAPI YAML to signal that these fields are only required in an API response message, and will be ignored if present in an API request message.

## Additional context
There are several other resources defined in TS 26.512 with mandatory fields that are also read-only and these should also be marked in the relevant OpenAPI YAML with the `readOnly: true` flag to improve the consistency between the Tables and the YAML.

**Comment by davidjwbbc** [comment]
This issue arose during implementing the feature while working on 5G-MAG/rt-5gms-application-function#70.

**Comment by rjb1000** [comment]
Change Request addressing this issue endorsed during yesterday's 3GPP SA4 _ad hoc_ call:
* TS 26.512
   * Rel-17 **CR0054** "[5GMS3, TEI17] Essential maintenance" in [S4aI230145](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/3GPP_SA4_AHOC_MTGs/SA4_MBS/Docs/S4aI230145.zip).
   * Rel-16: To be derived.

Revisions to be contributed to SA4#126 (Chicago).

**Comment by rjb1000** [comment]
Change Requests agreed at SA4#126 (Chicago):

* TS 26 512
  * Rel-17: **CR0054**r1 "Essential maintenance" in [S4-231631](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_126_Chicago/Docs/S4-231631.zip).
  * Rel-16: **CR0056** "Essential maintenance" in [S4-231632](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_126_Chicago/Docs/S4-231632.zip).

**Comment by rjb1000** [comment]
CR Packs approved at SA#102 (Edinburgh):
- Rel-16: [SP-231367](http://portal.3gpp.org/ngppapp/DownloadTDoc.aspx?contributionUid=SP-231367).
- Rel-17: [SP-231368](http://portal.3gpp.org/ngppapp/DownloadTDoc.aspx?contributionUid=SP-231368).

**Comment by rjb1000** [comment]
- TS 26.512 [V16.12.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-gc0.zip) published.
- TS 26.512 [V17.7.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-h70.zip) published.
- TS 26.512 [V18.0.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-i00.zip) published.
