### ISSUE TITLE
Update relevant sections to include normative work in Rel-17 on bandwidths

### ISSUE THREAD

**Issue by jordijoangimenez** [5G-MAG/Standards#9]
**Describe the bug**
The current version of the standard does not contain information about bandwidths or spectrum (e.g. Section 8, 5.5.3,...)

** Suggested solution **
Relevant sections can already be updated to reflect work in Rel-17 to specify 6,7 and 8 MHz carriers.

**Comment by dvargasparedero** [comment]
We need to describe this feature in ETSI TS 103 720.

**Comment by jordijoangimenez** [comment]
CRs - part 1
https://www.3gpp.org/ftp/TSG_RAN/TSG_RAN/TSGR_95e/Docs/RP-220840.zip (36.443)
https://www.3gpp.org/ftp/TSG_RAN/TSG_RAN/TSGR_95e/Docs/RP-220508.zip (36.300 36.306 36.331)

**Comment by jordijoangimenez** [comment]
Refer to: https://member.5g-mag.com/wg/CD-T/document/778

**Comment by rjb1000** [comment]
Can we make this change at this time?

Discussion on today's CD-T call suggested that 6/7/8 MHz is not included in 3GPP TS 36.104 Rel-17, so maybe we need to wait for Rel-18 before making this change.

**Comment by dvargasparedero** [comment]
Discussion and comments as per CD Work Items call on 23 June 2022:

- change of title to include "Bandwidths"
- check whether the description of 6/7/8 MHz in https://member.5g-mag.com/wg/CD-T/document/778 can be generalised to include the other existing bandwithds.
- In 26.346 the parameters are left open (reference to 36.104), check with Thomas S (Qualcomm)

**Comment by dvargasparedero** [comment]
As per discussion in CD Work Items call on 21 July 2022:

- @jordijoangimenez to Update section 5.5.3 including normative reference TS 136.104 for the description of parameter bandwidth. (This has been completed in  https://member.5g-mag.com/wg/CD-T/document/778)
- @haudiobe to check internally  description in section 8 and whether there are missing references from RAN1 specs that need to be completed.

**Comment by jordijoangimenez** [comment]
Pending actions are complete. Refer to: https://member.5g-mag.com/wg/CD-T/document/779
