### ISSUE TITLE
5GMSd -  Consumption Reporting - Clarification on duration property

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/Standards#90]
# Context
As part of the ConsumptionReportingUnit type as defined in 26.512 Table 11.3.3.2 the `mediaConsumed` property identifies the consumed media. In the case of DASH, the value of the `Representation@id` attribute shall be quoted. Moreover, the `startTime` and the `duration` property define the time when a consumption reporting unit started and the duration of a specific consumption unit respectively.

# Problem description
During the implementation the two following questions arose:

1. What value does `duration` hold in case the Representation referenced in `mediaConsumed` is still playing?
2. Should the last selected _ConsumptionReportingUnit_ be reported until a new Representation is selected? Otherwise, the duration can only be specified once.

# Suggested solution
A suggested solution is documented here: https://github.com/5G-MAG/rt-5gms-media-session-handler/issues/3#issuecomment-1735900907. In summary:

* The last (or only) Consumption Reporting Unit in a consumption report describes the media currently being consumed and indicates how long the Representation has been playing. If there is no change in the Representation when the next consumption report needs to be sent to the 5GMS AF, this Consumption Reporting Unit is repeated verbatim except for the _duration_ property which is updated with the longer duration. The last (or only) Consumption Reporting Unit in the final consumption report sent to the 5GMS AF therefore describes the last Representation consumed during the media streaming session.

Moreover, an explanation of the current implementation is provided here: https://github.com/5G-MAG/rt-5gms-media-stream-handler/issues/52

**Comment by rjb1000** [comment]
SA4 agrees that this should be clarified in TS 26.512.

**Comment by rjb1000** [comment]
Change Requests agreed at SA4#126 (Chicago):

* TS 26 512
  * Rel-17: **CR0054**r1 "Essential maintenance" in [S4-231631](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_126_Chicago/Docs/S4-231631.zip).
  * Rel-16: **CR0056** "Essential maintenance" in [S4-231632](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_126_Chicago/Docs/S4-231632.zip).

These provide additional guidance at the end of clause 4.7.4 on the population of consumption reporting units.

**Comment by rjb1000** [comment]
CR Packs approved at SA#102 (Edinburgh):
- Rel-16: [SP-231367](http://portal.3gpp.org/ngppapp/DownloadTDoc.aspx?contributionUid=SP-231367).
- Rel-17: [SP-231368](http://portal.3gpp.org/ngppapp/DownloadTDoc.aspx?contributionUid=SP-231368).

**Comment by rjb1000** [comment]
CR Packs approved at SA#102 (Edinburgh):
- Rel-16: [SP-231367](http://portal.3gpp.org/ngppapp/DownloadTDoc.aspx?contributionUid=SP-231367).
- Rel-17: [SP-231368](http://portal.3gpp.org/ngppapp/DownloadTDoc.aspx?contributionUid=SP-231368).

**Comment by rjb1000** [comment]
- TS 26.512 [V16.12.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-gc0.zip) published.
- TS 26.512 [V17.7.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-h70.zip) published.
- TS 26.512 [V18.0.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-i00.zip) published.
