### ISSUE TITLE
M5 Service Access Information - Inconsistency with ConsumptionReportingConfiguration.accessReporting

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/Standards#93]
# Context and problem description
TS 26.512-h60 defines the `accessReporting` property as part of the `clientConsumptionReportingConfiguration`. The following inconsistency was identified:

1. Table 7.7.3.1-1 defines the data model for the `ConsumptionReportingConfiguration`. In this case, `accessReporting` has a cardinality of `0..1`
2. Table 11.2.3.1-1 defines the `ServiceAccessInformation` resource. In this case, `accessReporting` has a cardinality of `1..1`
3. `TS26512_M5_ServiceAccessInformation.yaml` defines the corresponding YAML file. In this case, `accessReporting` is not a required field.

# Suggested solution
At this point, it is unclear if `accessReporting` is a mandatory field and shall be included in the ServiceAccessInformation. If it shall be included then the M1 data model also needs to be adjusted.

**Comment by rjb1000** [comment]
I agree that the inconsistency between table 11.2.3.1-1 and the OpenAPI definition needs to be corrected.

1. I think it would be alright to have the `accessReporting` property optional at M1 and mandatory at M5 provided that there was a clear specification that it needs to be set to `false` at M5 if omitted at M1.
2. Equally, it would be alright to have the `accessReporting` property optional at M5 (matching the cardinality at M1), but only if the semantics are clearly stated that it should be considered `false` if not present in the Service Access Information.

I'm not sure which of these options is better at this point. Option 2 seems more economical, but option 1 seems more explicit.

**Comment by dsilhavy** [comment]
My personal preference would be option 1 since it is more explicit as you described.

**Comment by rjb1000** [comment]
Option 1 also seems consistent with the approach for its siblings _samplePercentage_ and _locationReporting_.

It is also consistent with what is already specified in table 7.7.3.1-1.

**Comment by rjb1000** [comment]
Change Request addressing this issue endorsed during yesterday's 3GPP SA4 _ad hoc_ call:
* TS 26.512
   * Rel-17 **CR0054** "[5GMS3, TEI17] Essential maintenance" in [S4aI230145](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/3GPP_SA4_AHOC_MTGs/SA4_MBS/Docs/S4aI230145.zip).
   * Rel-16: To be derived.

Revisions to be contributed to SA4#126 (Chicago).

**Comment by rjb1000** [comment]
Change Requests agreed at SA4#126 (Chicago):

* TS 26 512
  * Rel-17: **CR0054**r1 "Essential maintenance" in [S4-231631](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_126_Chicago/Docs/S4-231631.zip).
  * Rel-16: **CR0056** "Essential maintenance" in [S4-231632](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_126_Chicago/Docs/S4-231632.zip).

Client consumption reporting configuration parameter _accessReporting_ is now required in Service Access Information.
Also clarified its population (as well as that of _samplePercentage_ and _locationReporting_ for consistency) in clause 11.2.3.1.

**Comment by rjb1000** [comment]
CR Packs approved at SA#102 (Edinburgh):
- Rel-16: [SP-231367](http://portal.3gpp.org/ngppapp/DownloadTDoc.aspx?contributionUid=SP-231367).
- Rel-17: [SP-231368](http://portal.3gpp.org/ngppapp/DownloadTDoc.aspx?contributionUid=SP-231368).

**Comment by rjb1000** [comment]
- TS 26.512 [V16.12.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-gc0.zip) published.
- TS 26.512 [V17.7.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-h70.zip) published.
- TS 26.512 [V18.0.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-i00.zip) published.
