### ISSUE TITLE
TS 26.512: M1 ConsumptionReportingConfiguration.reportingInterval value range not present in the OpenAPI YAML

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/Standards#96]
# Description
In TS 26.512, Table 7.7.3.1-1 says that the *reportingInterval*, if present, shall be greater than zero. However this limitation is not specified in the YAML OpenAPI description in Annex C.3.6.

This limitation should be included in the OpenAPI YAML for the ConsumptionReportingConfiguration schema.

# Suggested solution
Change the end of the YAML in Annex C.3.6 from
```yaml
components:
  schemas:
    ConsumptionReportingConfiguration:
      type: object
      description: "A representation of a Consumption Reporting Configuration resource."
      properties:
        reportingInterval:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DurationSec'
        samplePercentage:
          $ref: 'TS26512_CommonData.yaml#/components/schemas/Percentage'
        locationReporting:
          type: boolean
        accessReporting:
          type: boolean
```
to
```yaml
components:
  schemas:
    ConsumptionReportingConfiguration:
      type: object
      description: "A representation of a Consumption Reporting Configuration resource."
      properties:
        reportingInterval:
          minimum: 0
          exclusiveMinimum: true
          allOf:
            - $ref: 'TS29571_CommonData.yaml#/components/schemas/DurationSec'
        samplePercentage:
          $ref: 'TS26512_CommonData.yaml#/components/schemas/Percentage'
        locationReporting:
          type: boolean
        accessReporting:
          type: boolean
```

# Additional context
This issue based on TS 26.512 v17.6.0
  - Table 7.7.3.1-1
  - Annex C.3.6

**Comment by rjb1000** [comment]
@davidjwbbc: Have you verified that the suggested solution is workable with the OpenAPI Generator templates?

**Comment by rjb1000** [comment]
Change Request addressing this issue endorsed during yesterday's 3GPP SA4 _ad hoc_ call:
* TS 26.512
   * Rel-17 **CR0054** "[5GMS3, TEI17] Essential maintenance" in [S4aI230145](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/3GPP_SA4_AHOC_MTGs/SA4_MBS/Docs/S4aI230145.zip).
   * Rel-16: To be derived.

Revisions to be contributed to SA4#126 (Chicago).

**Comment by rjb1000** [comment]
Change Requests agreed at SA4#126 (Chicago):

* TS 26 512
  * Rel-17: **CR0054**r1 "Essential maintenance" in [S4-231631](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_126_Chicago/Docs/S4-231631.zip).
  * Rel-16: **CR0056** "Essential maintenance" in [S4-231632](https://www.3gpp.org/ftp/TSG_SA/WG4_CODEC/TSGS4_126_Chicago/Docs/S4-231632.zip).

Added bounds checking to OpenAPI YAML definition of _reportingInterval_ parameter in clause C.3.6.

**Comment by rjb1000** [comment]
CR Packs approved at SA#102 (Edinburgh):
- Rel-16: [SP-231367](http://portal.3gpp.org/ngppapp/DownloadTDoc.aspx?contributionUid=SP-231367).
- Rel-17: [SP-231368](http://portal.3gpp.org/ngppapp/DownloadTDoc.aspx?contributionUid=SP-231368).

**Comment by rjb1000** [comment]
- TS 26.512 [V16.12.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-gc0.zip) published.
- TS 26.512 [V17.7.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-h70.zip) published.
- TS 26.512 [V18.0.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-i00.zip) published.
