### ISSUE TITLE
TS 26.512 - Value of mediaPlayerEntry and mediaConsumed in Definition of ConsumptionReport format

### ISSUE THREAD

**Issue by shilinding** [5G-MAG/Standards#97]
# Context
In Table 11.3.3.1-1 and 11.3.3.2-1 of TS26.512, mediaPlayerEntry of ConsumptionReport format defined as below:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<p style='margin-top:3pt;margin-bottom:9pt;font-family:Arial;font-size:10.0pt'
lang=en-GB><span style='font-weight:bold'>Table&nbsp;11.3.3.1-1: Definition of
ConsumptionReport format</span></p>

<div style='direction:ltr'>

Property name | Data type | Cardinality | Description
-- | -- | -- | --
mediaPlayerEntry | AbsoluteUrl | 1..1 | Identifies   the Media Entry Point.   In the case   of DASH, thisshall be the URL of the MPD at reference point M4d.

</div>

</body>

</html>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<p style='margin-top:3pt;margin-bottom:9pt;font-family:Arial;font-size:10.0pt'
lang=en-GB><span style='font-weight:bold'>Table&nbsp;11.3.3.2-1: Definition of
type ConsumptionReportingUnit</span></p>

<div style='direction:ltr'>

Property name | Data type | Cardinality | Description
-- | -- | -- | --
mediaConsumed | string | 1..1 | Identifies   the media consumed.   In the case   of DASH, the value of the Representation@id attribute shall be quoted.

</div>

</body>

</html>

# Problem description
In the defintion, there only define the values of mediaPlayerEntry and mediaConsumed in the case of DASH, but not define their values  in other cases.

**Comment by rjb1000** [comment]
Thanks for raising this. Generally speaking, the 5G Media Streaming specifications are primarily targeting MPEG-DASH or MPEG-CMAF, but the use of other formats is not precluded. In particular, HLS is in common usage on mobile platforms.

I think it's a good question for the SA4 experts whether the two tables you point out above could provide more helpful mappings to HLS, at least.

**Comment by shilinding** [comment]
Thanks @rjb1000. I think we can mainly consider about DASH, but as a standard spec it mentioned as " In case of..." but no "else", this may make others feels like it's incompleted and confused.

**Comment by rjb1000** [comment]
> as a standard spec it mentioned as " In case of..." but no "else" branch, this may make others feels like it's incompleted and confused.

Incompleteness isn't necessarily a problem in itself: being completely comprehensive is rarely possible in a specification. In this case SA4 may decide to add text covering HLS, but it's very unlikely it would write anything about Smooth Streaming or HDS, for example. So this is primarily a question of how comprehensive the specification needs to be on a sliding scale.

> BTW, there is a typo in "thisshall" of Table 11.3.3.1-1(miss a space between "this" and "shall").

Thanks. That's an easy fix to include in the next maintenance Change Request.

**Comment by rjb1000** [comment]
@haudiobe: As a first suggestion, we could specify that these two fields are undefined for cases other than DASH.

Unfortunately, this isn't great for interoperability.

@dsilhavy suggests the HLS Master Playlist URL and the HLS Media Playlist URL respectively.

@dsilhavy also pointed out the overlap with the `RepSwitchList/RepSwitchEvent` in the QoE metrics report in TS 26.247.

More discussion required with SA4 about whether this consumption report is what we want, or whether DASH-IF CMCD is a better fit.

Possible compromise:
- Specify these two properties explicitly for HLS and say that they are undefined for other formats.

@haudiobe: Need to check if these values can actually be accessed via a suitable client API.

**Comment by rjb1000** [comment]
@haudiobe: It's useful for some Use Cases that media is being consumed (to count the number of active sessions). Also useful to know which Representation is being consumed. Possible mistake in the reporting API: better to report the Adaptation Set than the Representation.

(Note that the Adaptation Set ID is not mandatory in the DASH MPD at present!)

**Comment by rjb1000** [comment]
Agreement for SA4#126 is to add a sentence that these two fields are undefined for cases other than DASH.

**Comment by rjb1000** [comment]
CR Packs approved at SA#102 (Edinburgh):
- Rel-16: [SP-231367](http://portal.3gpp.org/ngppapp/DownloadTDoc.aspx?contributionUid=SP-231367).
- Rel-17: [SP-231368](http://portal.3gpp.org/ngppapp/DownloadTDoc.aspx?contributionUid=SP-231368).

**Comment by rjb1000** [comment]
- TS 26.512 [V16.12.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-gc0.zip) published.
- TS 26.512 [V17.7.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-h70.zip) published.
- TS 26.512 [V18.0.0](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/26512-i00.zip) published.
